using System.Collections.Immutable;
using static Onnxify.ModelGenerator.Helpers.TextHelper;
using static Onnxify.ModelGenerator.OnnxModelGenerator;

namespace Onnxify.ModelGenerator.Services;

internal sealed class OnnxRuntimeInferencePrinter
{
    private static readonly XmlDocumentationPrinter _documentationPrinter = new();

    internal string GenerateSource(ModelGenerationSpecification specification)
    {
        var inputTypeName = $"{specification.ClassName}Inputs";
        var outputTypeName = $"{specification.ClassName}Outputs";

        return $$"""
        // <auto-generated/>
        #nullable enable
            
        using System;
        using System.Collections.Generic;
        using System.Linq;
        using System.Threading;
        using System.Threading.Tasks;
        using Microsoft.ML.OnnxRuntime;
        using Microsoft.ML.OnnxRuntime.Tensors;

        namespace {{specification.NamespaceName}}
        {
            {{Indent(BuildWrapperType(specification, inputTypeName, outputTypeName), 1)}}

            {{Indent(BuildInputType(specification, inputTypeName), 1)}}

            {{Indent(BuildOutputType(specification, outputTypeName), 1)}}
        }

        #nullable restore
        """;
    }

    private static string BuildInputType(
        ModelGenerationSpecification specification,
        string inputTypeName
    )
    {
        var props = specification.Inputs
            .Select(static input =>
            {
                return $$"""
                {{_documentationPrinter.InputProperty(input)}}
                public {{(input.IsRequired ? "required " : string.Empty)}}Tensor<{{input.ElementClrTypeName}}>{{(input.IsRequired ? string.Empty : "?")}} {{input.PropertyName}} { get; init; }
                """;
            })
            .ToArray();

        var code = string.Join("\n\n", props);

        return $$"""
        {{_documentationPrinter.TensorCollectionType(
            summary: $"Collects the tensors supplied to {specification.ClassName}.",
            tensors: specification.Inputs,
            roleLabel: "Input property"
        )}}
        public sealed class {{inputTypeName}}
        {
            {{Indent(code, 1)}}
        }
        """;
    }

    private static string BuildOutputType(
        ModelGenerationSpecification specification,
        string outputTypeName
    )
    {
        var props = specification.Outputs
            .Select(static output =>
            {
                return $$"""
                {{_documentationPrinter.OutputProperty(output)}}
                public Tensor<{{output.ElementClrTypeName}}> {{output.PropertyName}} => GetTensor<{{output.ElementClrTypeName}}>("{{Escape(output.OnnxName)}}");
                """;
            })
            .ToArray();

        var code = string.Join("\n\n", props);

        return $$"""
        {{_documentationPrinter.TensorCollectionType(
            summary: $"Provides typed access to the outputs produced by {specification.ClassName}.",
            tensors: specification.Outputs,
            roleLabel: "Output property"
        )}}
        public sealed class {{outputTypeName}} : IDisposable
        {
            private readonly IDisposableReadOnlyCollection<DisposableNamedOnnxValue>? _results;
            private readonly IReadOnlyCollection<OrtValue>? _ortResults;
            private readonly Dictionary<string, DisposableNamedOnnxValue>? _values;
            private readonly Dictionary<string, OrtValue>? _ortValues;

            internal {{outputTypeName}}(IDisposableReadOnlyCollection<DisposableNamedOnnxValue> results)
            {
                if (results is null)
                {
                    throw new ArgumentNullException(nameof(results));
                }

                _results = results;
                _values = new Dictionary<string, DisposableNamedOnnxValue>(StringComparer.Ordinal);
                _ortResults = null;
                _ortValues = null;
                foreach (var value in results)
                {
                    _values[value.Name] = value;
                }
            }

            internal {{outputTypeName}}(
                IReadOnlyCollection<OrtValue> results,
                IReadOnlyList<string> outputNames
            )
            {
                if (results is null)
                {
                    throw new ArgumentNullException(nameof(results));
                }

                if (outputNames is null)
                {
                    throw new ArgumentNullException(nameof(outputNames));
                }

                if (results.Count != outputNames.Count)
                {
                    throw new InvalidOperationException($"ONNX Runtime returned {results.Count} output values for {outputNames.Count} requested output names.");
                }

                _results = null;
                _values = null;
                _ortResults = results;
                _ortValues = new Dictionary<string, OrtValue>(StringComparer.Ordinal);

                var index = 0;
                foreach (var value in results)
                {
                    _ortValues[outputNames[index]] = value;
                    index++;
                }
            }

            {{Indent(XmlSummary("Gets the raw ONNX Runtime outputs returned by the inference session."), 1)}}
            public IDisposableReadOnlyCollection<DisposableNamedOnnxValue> Raw => _results ?? throw new NotSupportedException("Raw DisposableNamedOnnxValue outputs are not available for asynchronous OrtValue-backed inference results. Use the typed output properties or GetTensor<T>(string) instead.");
                
            {{Indent(code, 1)}}

            {{Indent(_documentationPrinter.GetTensor(), 1)}}
            public Tensor<T> GetTensor<T>(string name)
                where T : unmanaged
            {
                if (string.IsNullOrWhiteSpace(name))
                {
                    throw new ArgumentException("Output name must be provided.", nameof(name));
                }

                if (_values is not null)
                {
                    if (!_values.TryGetValue(name, out var value))
                    {
                        throw new KeyNotFoundException($"The output '{name}' was not returned by the model.");
                    }

                    var tensor = value.AsTensor<T>();
                    if (tensor is null)
                    {
                        throw new InvalidOperationException($"The output '{name}' is not a tensor of the requested type {typeof(T).FullName}.");
                    }

                    return tensor;
                }

                if (_ortValues is null || !_ortValues.TryGetValue(name, out var ortValue))
                {
                    throw new KeyNotFoundException($"The output '{name}' was not returned by the model.");
                }

                return CreateDenseTensor<T>(ortValue);
            }

            {{Indent(XmlSummary("Releases the native ONNX Runtime output values for this inference result."), 1)}}
            public void Dispose()
            {
                _results?.Dispose();

                if (_ortResults is not null)
                {
                    foreach (var result in _ortResults)
                    {
                        result.Dispose();
                    }
                }
            }

            private static Tensor<T> CreateDenseTensor<T>(OrtValue value)
                where T : unmanaged
            {
                var shape = value.GetTensorTypeAndShape().Shape;
                var dimensions = new int[shape.Length];
                for (var index = 0; index < shape.Length; index++)
                {
                    dimensions[index] = checked((int)shape[index]);
                }

                return new DenseTensor<T>(value.GetTensorDataAsSpan<T>().ToArray(), dimensions);
            }
        }
        """;
    }

    private static string BuildWrapperType(
        ModelGenerationSpecification specification,
        string inputTypeName,
        string outputTypeName
    )
    {
        var outputNames = string.Join(
            "\n",
            specification.Outputs.Select(static output => $"\"{Escape(output.OnnxName)}\","));

        var constructors = $$"""
        {{XmlSummary($"Creates a {specification.ClassName} that loads the model from DefaultModelPath.")}}
        public {{specification.ClassName}}()
            : this(DefaultModelPath, null)
        {
        }

        {{XmlSummary($"Creates a {specification.ClassName} that loads the model from DefaultModelPath.")}}
        {{XmlParam("sessionOptions", "Optional ONNX Runtime session options used when constructing the inference session.")}}
        public {{specification.ClassName}}(SessionOptions? sessionOptions)
            : this(DefaultModelPath, sessionOptions)
        {
        }

        {{XmlSummary($"Creates a {specification.ClassName} from an ONNX model file path.")}}
        {{XmlParam("modelPath", "Path to the ONNX model file to load.")}}
        public {{specification.ClassName}}(string modelPath)
            : this(modelPath, null)
        {
        }

        {{XmlSummary($"Creates a {specification.ClassName} from an ONNX model file path.")}}
        {{XmlParam("modelPath", "Path to the ONNX model file to load.")}}
        {{XmlParam("sessionOptions", "Optional ONNX Runtime session options used when constructing the inference session.")}}
        public {{specification.ClassName}}(string modelPath, SessionOptions? sessionOptions)
            : base(modelPath, sessionOptions)
        {
        }

        {{XmlSummary($"Creates a {specification.ClassName} from the raw bytes of an ONNX model.")}}
        {{XmlParam("modelBytes", "The raw ONNX model bytes to load into the inference session.")}}
        public {{specification.ClassName}}(byte[] modelBytes)
            : this(modelBytes, null)
        {
        }

        {{XmlSummary($"Creates a {specification.ClassName} from the raw bytes of an ONNX model.")}}
        {{XmlParam("modelBytes", "The raw ONNX model bytes to load into the inference session.")}}
        {{XmlParam("sessionOptions", "Optional ONNX Runtime session options used when constructing the inference session.")}}
        public {{specification.ClassName}}(byte[] modelBytes, SessionOptions? sessionOptions)
            : base(modelBytes, sessionOptions)
        {
        }
        """;

        var runMethods = specification.Inputs.Length == 0
            ? BuildParameterlessRunMethods(specification, outputTypeName)
            : BuildInputRunMethods(specification, inputTypeName, outputTypeName);

        return $$"""
        {{XmlSummary($"Provides a typed ONNX Runtime wrapper for the model file '{specification.FileName}'.")}}
        public sealed class {{specification.ClassName}} : Onnxify.Abstractions.InferenceSessionModel
        {
            {{Indent(XmlSummary("Gets the model path relative to the consuming project directory."), 1)}}
            public const string MODEL_PROJECT_RELATIVE_PATH = {{ToVerbatimStringLiteral(specification.ProjectRelativePath)}};

            {{Indent(XmlSummary("Gets the default runtime path used to locate the ONNX model beside the application output."), 1)}}
            public static string DefaultModelPath => GetDefaultModelPath(MODEL_PROJECT_RELATIVE_PATH);

            {{Indent(_documentationPrinter.MetadataCollection("input", specification.Inputs), 1)}}
            public static IReadOnlyList<Onnxify.OnnxValue> Inputs { get; } = CreateInputs();

            {{Indent(_documentationPrinter.MetadataCollection("output", specification.Outputs), 1)}}
            public static IReadOnlyList<Onnxify.OnnxValue> Outputs { get; } = CreateOutputs();

            {{Indent(XmlSummary("Gets the output names requested from ONNX Runtime during inference."), 1)}}
            public static IReadOnlyList<string> OutputNames { get; } = new string[]
            {
                {{Indent(outputNames, 2)}}
            };

            private static IReadOnlyList<Onnxify.OnnxValue> CreateInputs()
            {
                {{Indent(BuildOnnxValueMetadata(specification.Inputs), 2)}}
            }

            private static IReadOnlyList<Onnxify.OnnxValue> CreateOutputs()
            {
                {{Indent(BuildOnnxValueMetadata(specification.Outputs), 2)}}
            }

            {{Indent(BuildCreateInputOrtValueMethod(), 1)}}

            {{Indent(BuildCreateOutputOrtValuesMethod(specification), 1)}}

            {{Indent(constructors, 1)}}

            {{Indent(runMethods, 1)}}
        }
        """;
    }

    private static string BuildParameterlessRunMethods(
        ModelGenerationSpecification specification,
        string outputTypeName
    )
    {
        return $$"""
        {{XmlSummary("Runs inference for a model with no required inputs.")}}
        {{XmlReturns($"The typed {outputTypeName} wrapper over the ONNX Runtime outputs.")}}
        public {{outputTypeName}} Run()
        {
            return Run(null);
        }

        {{XmlSummary("Runs inference for a model with no required inputs.")}}
        {{XmlParam("runOptions", "Optional ONNX Runtime run options applied to this inference invocation.")}}
        {{XmlReturns($"The typed {outputTypeName} wrapper over the ONNX Runtime outputs.")}}
        public {{outputTypeName}} Run(RunOptions? runOptions)
        {
            var namedInputs = new List<NamedOnnxValue>(0);
            {{Indent(BuildRunInvocation(outputTypeName), 1)}}
        }

        {{XmlSummary("Runs inference asynchronously for a model with no required inputs.")}}
        {{XmlParam("cancellationToken", "Token used to request cancellation for this inference invocation.")}}
        {{XmlReturns($"A task that produces the typed {outputTypeName} wrapper over the ONNX Runtime outputs.")}}
        public Task<{{outputTypeName}}> RunAsync(CancellationToken cancellationToken = default)
        {
            return RunAsync(
                runOptions: null,
                cancellationToken: cancellationToken
            );
        }

        {{XmlSummary("Runs inference asynchronously for a model with no required inputs.")}}
        {{XmlParam("runOptions", "Optional ONNX Runtime run options applied to this inference invocation.")}}
        {{XmlParam("cancellationToken", "Token used to request cancellation for this inference invocation.")}}
        {{XmlReturns($"A task that produces the typed {outputTypeName} wrapper over the ONNX Runtime outputs.")}}
        public async Task<{{outputTypeName}}> RunAsync(
            RunOptions? runOptions,
            CancellationToken cancellationToken = default
        )
        {
            var inputNames = Array.Empty<string>();
            var inputValues = Array.Empty<OrtValue>();
            {{Indent(BuildAsyncRunInvocation(outputTypeName, hasInputValues: false), 1)}}
        }
        """;
    }

    private static string BuildInputRunMethods(
        ModelGenerationSpecification specification,
        string inputTypeName,
        string outputTypeName
    )
    {
        var orderedInputs = specification.Inputs
            .OrderByDescending(static x => x.IsRequired)
            .ToArray();

        var namedInputs = string.Join(
            "\n",
            specification.Inputs.Select(static input =>
                input.IsRequired
                    ? $"namedInputs.Add(NamedOnnxValue.CreateFromTensor(\"{Escape(input.OnnxName)}\", inputs.{input.PropertyName} ?? throw new InvalidOperationException(\"Model input '{Escape(input.OnnxName)}' must be provided.\")));"
                    : $$"""
                    if (inputs.{{input.PropertyName}} is not null)
                    {
                        namedInputs.Add(NamedOnnxValue.CreateFromTensor("{{Escape(input.OnnxName)}}", inputs.{{input.PropertyName}}));
                    }
                    """));

        var signature = string.Join(", ", orderedInputs.Select(BuildTensorMethodParameterSignature));
        var signatureWithRunOptions = BuildRunMethodSignatureWithRunOptions(orderedInputs);
        var asyncSignature = BuildAsyncRunMethodSignature(orderedInputs);
        var asyncSignatureWithRunOptions = BuildAsyncRunMethodSignatureWithRunOptions(orderedInputs);
        var assignments = string.Join(
            "\n",
            orderedInputs.Select(static x => $"{x.PropertyName} = {x.MethodParameterName},"));
        var fixedInputs = string.Join(
            "\n",
            specification.Inputs.Select(static input =>
                input.IsRequired
                    ? $$"""
                    inputNames.Add("{{Escape(input.OnnxName)}}");
                    inputValues.Add(CreateInputOrtValue(inputs.{{input.PropertyName}} ?? throw new InvalidOperationException("Model input '{{Escape(input.OnnxName)}}' must be provided.")));
                    """
                    : $$"""
                    if (inputs.{{input.PropertyName}} is not null)
                    {
                        inputNames.Add("{{Escape(input.OnnxName)}}");
                        inputValues.Add(CreateInputOrtValue(inputs.{{input.PropertyName}}));
                    }
                    """));

        return $$"""
        {{XmlSummary("Runs inference using the supplied input object.")}}
        {{XmlParam("inputs", $"The {inputTypeName} instance containing tensors for each required model input.")}}
        {{XmlReturns($"The typed {outputTypeName} wrapper over the ONNX Runtime outputs.")}}
        public {{outputTypeName}} Run({{inputTypeName}} inputs)
        {
            return Run(inputs, null);
        }

        {{XmlSummary("Runs inference using the supplied input object.")}}
        {{XmlParam("inputs", $"The {inputTypeName} instance containing tensors for each required model input.")}}
        {{XmlParam("runOptions", "Optional ONNX Runtime run options applied to this inference invocation.")}}
        {{XmlReturns($"The typed {outputTypeName} wrapper over the ONNX Runtime outputs.")}}
        public {{outputTypeName}} Run({{inputTypeName}} inputs, RunOptions? runOptions)
        {
            if (inputs is null)
            {
                throw new ArgumentNullException(nameof(inputs));
            }

            var namedInputs = new List<NamedOnnxValue>({{specification.Inputs.Length}});
            {{Indent(namedInputs, 1)}}

            {{Indent(BuildRunInvocation(outputTypeName), 1)}}
        }

        {{XmlSummary("Runs inference using individual tensor arguments for each model input.")}}
        {{_documentationPrinter.TensorParameters(orderedInputs)}}
        {{XmlReturns($"The typed {outputTypeName} wrapper over the ONNX Runtime outputs.")}}
        public {{outputTypeName}} Run({{signature}})
        {
            return Run(
                inputs: new {{inputTypeName}}
                {
                    {{Indent(assignments, 3)}}
                }, 
                runOptions: null
            );
        }

        {{XmlSummary("Runs inference using individual tensor arguments for each model input.")}}
        {{_documentationPrinter.TensorParameters(orderedInputs)}}
        {{XmlParam("runOptions", "Optional ONNX Runtime run options applied to this inference invocation.")}}
        {{XmlReturns($"The typed {outputTypeName} wrapper over the ONNX Runtime outputs.")}}
        public {{outputTypeName}} Run({{signatureWithRunOptions}})
        {
            return Run(
                inputs: new {{inputTypeName}}
                {
                    {{Indent(assignments, 3)}}
                }, 
                runOptions: runOptions
            );
        }

        {{XmlSummary("Runs inference asynchronously using the supplied input object.")}}
        {{XmlParam("inputs", $"The {inputTypeName} instance containing tensors for each required model input.")}}
        {{XmlParam("cancellationToken", "Token used to request cancellation for this inference invocation.")}}
        {{XmlReturns($"A task that produces the typed {outputTypeName} wrapper over the ONNX Runtime outputs.")}}
        public Task<{{outputTypeName}}> RunAsync(
            {{inputTypeName}} inputs,
            CancellationToken cancellationToken = default
        )
        {
            return RunAsync(
                inputs: inputs,
                runOptions: null,
                cancellationToken: cancellationToken
            );
        }

        {{XmlSummary("Runs inference asynchronously using the supplied input object.")}}
        {{XmlParam("inputs", $"The {inputTypeName} instance containing tensors for each required model input.")}}
        {{XmlParam("runOptions", "Optional ONNX Runtime run options applied to this inference invocation.")}}
        {{XmlParam("cancellationToken", "Token used to request cancellation for this inference invocation.")}}
        {{XmlReturns($"A task that produces the typed {outputTypeName} wrapper over the ONNX Runtime outputs.")}}
        public async Task<{{outputTypeName}}> RunAsync(
            {{inputTypeName}} inputs,
            RunOptions? runOptions,
            CancellationToken cancellationToken = default
        )
        {
            if (inputs is null)
            {
                throw new ArgumentNullException(nameof(inputs));
            }

            var inputNames = new List<string>({{specification.Inputs.Length}});
            var inputValues = new List<OrtValue>({{specification.Inputs.Length}});
            {{Indent(fixedInputs, 1)}}

            {{Indent(BuildAsyncRunInvocation(outputTypeName, hasInputValues: true), 1)}}
        }

        {{XmlSummary("Runs inference asynchronously using individual tensor arguments for each model input.")}}
        {{_documentationPrinter.TensorParameters(orderedInputs)}}
        {{XmlParam("cancellationToken", "Token used to request cancellation for this inference invocation.")}}
        {{XmlReturns($"A task that produces the typed {outputTypeName} wrapper over the ONNX Runtime outputs.")}}
        public Task<{{outputTypeName}}> RunAsync({{asyncSignature}})
        {
            return RunAsync(
                inputs: new {{inputTypeName}}
                {
                    {{Indent(assignments, 3)}}
                },
                runOptions: null,
                cancellationToken: cancellationToken
            );
        }

        {{XmlSummary("Runs inference asynchronously using individual tensor arguments for each model input.")}}
        {{_documentationPrinter.TensorParameters(orderedInputs)}}
        {{XmlParam("runOptions", "Optional ONNX Runtime run options applied to this inference invocation.")}}
        {{XmlParam("cancellationToken", "Token used to request cancellation for this inference invocation.")}}
        {{XmlReturns($"A task that produces the typed {outputTypeName} wrapper over the ONNX Runtime outputs.")}}
        public Task<{{outputTypeName}}> RunAsync({{asyncSignatureWithRunOptions}})
        {
            return RunAsync(
                inputs: new {{inputTypeName}}
                {
                    {{Indent(assignments, 3)}}
                },
                runOptions: runOptions,
                cancellationToken: cancellationToken
            );
        }
        """;
    }

    private static string BuildRunInvocation(string outputTypeName)
    {
        return $$"""
        IDisposableReadOnlyCollection<DisposableNamedOnnxValue> results;
        if (runOptions is null)
        {
            results = OutputNames.Count == 0
                ? Session.Run(namedInputs)
                : Session.Run(namedInputs, OutputNames);
        }
        else
        {
            results = Session.Run(namedInputs, OutputNames, runOptions);
        }

        return new {{outputTypeName}}(results);
        """;
    }

    private static string BuildAsyncRunInvocation(
        string outputTypeName,
        bool hasInputValues
    )
    {
        var disposeInputValues = hasInputValues
            ? """
            foreach (var inputValue in inputValues)
            {
                inputValue.Dispose();
            }
            """
            : string.Empty;

        return $$"""
        RunOptions? generatedRunOptions = null;
        RunOptions effectiveRunOptions;
        if (runOptions is null)
        {
            generatedRunOptions = new RunOptions();
            effectiveRunOptions = generatedRunOptions;
        }
        else
        {
            effectiveRunOptions = runOptions;
        }

        var originalTerminate = effectiveRunOptions.Terminate;
        var cancellationRegistration = cancellationToken.CanBeCanceled
            ? cancellationToken.Register(
                static state =>
                {
                    if (state is RunOptions options)
                    {
                        options.Terminate = true;
                    }
                },
                effectiveRunOptions
            )
            : default;

        var outputValues = CreateOutputOrtValues();
        var outputValuesTransferred = false;

        try
        {
            cancellationToken.ThrowIfCancellationRequested();

            var results = await Session.RunAsync(
                effectiveRunOptions,
                inputNames,
                inputValues,
                OutputNames,
                outputValues
            );

            outputValuesTransferred = true;
            return new {{outputTypeName}}(results, OutputNames);
        }
        finally
        {
            cancellationRegistration.Dispose();
            effectiveRunOptions.Terminate = originalTerminate;
            if (!outputValuesTransferred)
            {
                foreach (var outputValue in outputValues)
                {
                    outputValue.Dispose();
                }
            }
            {{Indent(disposeInputValues, 1)}}
            generatedRunOptions?.Dispose();
        }
        """;
    }

    private static string BuildOnnxValueMetadata(
        ImmutableArray<ModelTensorContract> tensors
    )
    {
        if (tensors.Length == 0)
        {
            return "return Array.Empty<Onnxify.OnnxValue>();";
        }

        var entries = string.Join("\n", tensors.Select(BuildOnnxValueMetadataEntry));

        return $$"""
        return new Onnxify.OnnxValue[]
        {
            {{Indent(entries, 1)}}
        };
        """;
    }

    private static string BuildOnnxValueMetadataEntry(
        ModelTensorContract tensor
    )
    {
        var tensorTypeExpression = BuildOnnxTensorTypeExpression(tensor);

        return $$"""
        new Onnxify.OnnxValue<Onnxify.OnnxTensorType>(
            name: "{{Escape(tensor.OnnxName)}}",
            type: {{Indent(tensorTypeExpression, 1)}}
        ),
        """;
    }

    private static string BuildOnnxTensorTypeExpression(ModelTensorContract tensor)
    {
        if (tensor.Shape.Length == 0)
        {
            return $$"""
                new Onnxify.OnnxTensorType(
                    type: typeof({{tensor.ElementClrTypeName}}),
                    shape: Onnxify.OnnxTensorShape.Create(Array.Empty<Onnxify.OnnxDimension>()),
                    denotation: {{tensor.DenotationLiteral}}
                )
                """;
        }

        var dimensions = string.Join("\n", tensor.Shape.Select(BuildOnnxDimensionExpression));

        return $$"""
        Onnxify.OnnxTensorType.Create<{{tensor.ElementClrTypeName}}>(
            shape: new Onnxify.OnnxDimension[]
            {
                {{Indent(dimensions, 2)}}
            },
            denotation: {{tensor.DenotationLiteral}}
        )
        """;
    }

    private static string BuildOnnxDimensionExpression(ModelDimensionContract dimension)
    {
        if (dimension.NumericValueLiteral is not null)
        {
            return dimension.DenotationLiteral is null
                ? $"{dimension.NumericValueLiteral},"
                : $"new Onnxify.OnnxDimension<long>({dimension.NumericValueLiteral}, {dimension.DenotationLiteral}),";
        }

        if (dimension.SymbolicNameLiteral is not null)
        {
            return dimension.DenotationLiteral is null
                ? $"{dimension.SymbolicNameLiteral},"
                : $"new Onnxify.OnnxDimension<string>({dimension.SymbolicNameLiteral}, {dimension.DenotationLiteral}),";
        }

        return dimension.DenotationLiteral is null
            ? "new Onnxify.OnnxDimensionNone(),"
            : $"new Onnxify.OnnxDimensionNone({dimension.DenotationLiteral}),";
    }

    private static string BuildTensorMethodParameterSignature(ModelTensorContract tensor)
    {
        return tensor.IsRequired
            ? $"Tensor<{tensor.ElementClrTypeName}> {tensor.MethodParameterName}"
            : $"Tensor<{tensor.ElementClrTypeName}>? {tensor.MethodParameterName} = null";
    }

    private static string BuildCreateInputOrtValueMethod()
    {
        return """
        private static OrtValue CreateInputOrtValue<T>(Tensor<T> tensor)
            where T : unmanaged
        {
            if (tensor is null)
            {
                throw new ArgumentNullException(nameof(tensor));
            }

            var shape = new long[tensor.Dimensions.Length];
            for (var index = 0; index < tensor.Dimensions.Length; index++)
            {
                shape[index] = tensor.Dimensions[index];
            }

            return OrtValue.CreateTensorValueFromMemory<T>(tensor.ToArray(), shape);
        }
        """;
    }

    private static string BuildCreateOutputOrtValuesMethod(ModelGenerationSpecification specification)
    {
        if (specification.Outputs.Length == 0)
        {
            return """
            private static OrtValue[] CreateOutputOrtValues()
            {
                return Array.Empty<OrtValue>();
            }
            """;
        }

        var outputValues = string.Join(
            "\n",
            specification.Outputs.Select(BuildCreateOutputOrtValueExpression));

        return $$"""
        private static OrtValue[] CreateOutputOrtValues()
        {
            return new OrtValue[]
            {
                {{Indent(outputValues, 2)}}
            };
        }

        private static OrtValue CreateOutputOrtValue(
            string outputName,
            TensorElementType elementType,
            long[] shape
        )
        {
            if (shape.Any(static dimension => dimension < 0))
            {
                throw new NotSupportedException($"Asynchronous ONNX Runtime inference requires statically known output dimensions for output '{outputName}'. Use Run(...) for models with dynamic output shapes.");
            }

            return OrtValue.CreateAllocatedTensorValue(
                OrtAllocator.DefaultInstance,
                elementType,
                shape
            );
        }
        """;
    }

    private static string BuildCreateOutputOrtValueExpression(ModelTensorContract output)
    {
        var elementTypeName = output.ElementClrTypeName switch
        {
            "float" => "Float",
            "double" => "Double",
            "long" => "Int64",
            "ulong" => "UInt64",
            "int" => "Int32",
            "uint" => "UInt32",
            "short" => "Int16",
            "ushort" => "UInt16",
            "sbyte" => "Int8",
            "byte" => "UInt8",
            "bool" => "Bool",
            "string" => "String",
            "Float16" => "Float16",
            "BFloat16" => "BFloat16",
            _ => null,
        };

        if (elementTypeName is null)
        {
            return $"throw new NotSupportedException(\"Asynchronous ONNX Runtime inference does not support preallocating output '{Escape(output.OnnxName)}' with element type '{Escape(output.ElementClrTypeName)}'. Use Run(...) for this model.\"),";
        }

        var shape = output.Shape.Length == 0
            ? "Array.Empty<long>()"
            : $"new long[] {{ {string.Join(", ", output.Shape.Select(BuildOutputDimensionLiteral))} }}";

        return $"CreateOutputOrtValue(\"{Escape(output.OnnxName)}\", TensorElementType.{elementTypeName}, {shape}),";
    }

    private static string BuildOutputDimensionLiteral(ModelDimensionContract dimension)
    {
        return dimension.NumericValueLiteral is null
            ? "-1L"
            : dimension.NumericValueLiteral;
    }

    private static string BuildRunMethodSignatureWithRunOptions(
        IReadOnlyList<ModelTensorContract> orderedInputs
    )
    {
        var requiredInputs = orderedInputs
            .Where(static x => x.IsRequired)
            .Select(BuildTensorMethodParameterSignature);
        var optionalInputs = orderedInputs
            .Where(static x => !x.IsRequired)
            .Select(BuildTensorMethodParameterSignature);

        return string.Join(
            ", ",
            requiredInputs
                .Concat(["RunOptions? runOptions"])
                .Concat(optionalInputs)
        );
    }

    private static string BuildAsyncRunMethodSignature(
        IReadOnlyList<ModelTensorContract> orderedInputs
    )
    {
        return string.Join(
            ", ",
            orderedInputs
                .Select(BuildTensorMethodParameterSignature)
                .Concat(["CancellationToken cancellationToken = default"])
        );
    }

    private static string BuildAsyncRunMethodSignatureWithRunOptions(
        IReadOnlyList<ModelTensorContract> orderedInputs
    )
    {
        var requiredInputs = orderedInputs
            .Where(static x => x.IsRequired)
            .Select(BuildTensorMethodParameterSignature);
        var optionalInputs = orderedInputs
            .Where(static x => !x.IsRequired)
            .Select(BuildTensorMethodParameterSignature);

        return string.Join(
            ", ",
            requiredInputs
                .Concat(["RunOptions? runOptions"])
                .Concat(optionalInputs)
                .Concat(["CancellationToken cancellationToken = default"])
        );
    }

}

