using System.Collections.Immutable;
using static Onnxify.ModelGenerator.Helpers.TextHelper;
using static Onnxify.ModelGenerator.OnnxModelGenerator;

namespace Onnxify.ModelGenerator.Services;

internal sealed class OnnxRuntimeInferencePrinter
{
    private static readonly XmlDocumentationPrinter _documentationPrinter = new();

    internal string GenerateSource(ModelGenerationSpecification specification)
    {
        var inputTypeName = $"{specification.ClassName}Inputs";
        var outputTypeName = $"{specification.ClassName}Outputs";

        return $$"""
        // <auto-generated/>
        #nullable enable
            
        using System;
        using System.Collections.Generic;
        using System.IO;
        using Microsoft.ML.OnnxRuntime;
        using Microsoft.ML.OnnxRuntime.Tensors;

        namespace {{specification.NamespaceName}}
        {
            {{Indent(BuildWrapperType(specification, inputTypeName, outputTypeName), 1)}}

            {{Indent(BuildInputType(specification, inputTypeName), 1)}}

            {{Indent(BuildOutputType(specification, outputTypeName), 1)}}
        }

        #nullable restore
        """;
    }

    private static string BuildInputType(
        ModelGenerationSpecification specification,
        string inputTypeName
    )
    {
        var props = specification.Inputs
            .Select(static input =>
            {
                return $$"""
                {{_documentationPrinter.InputProperty(input)}}
                public {{(input.IsRequired ? "required " : string.Empty)}}Tensor<{{input.ElementClrTypeName}}>{{(input.IsRequired ? string.Empty : "?")}} {{input.PropertyName}} { get; init; }
                """;
            })
            .ToArray();

        var code = string.Join("\n\n", props);

        return $$"""
        {{_documentationPrinter.TensorCollectionType(
            summary: $"Collects the tensors supplied to {specification.ClassName}.",
            tensors: specification.Inputs,
            roleLabel: "Input property"
        )}}
        public sealed class {{inputTypeName}}
        {
            {{Indent(code, 1)}}
        }
        """;
    }

    private static string BuildOutputType(
        ModelGenerationSpecification specification,
        string outputTypeName
    )
    {
        var props = specification.Outputs
            .Select(static output =>
            {
                return $$"""
                {{_documentationPrinter.OutputProperty(output)}}
                public Tensor<{{output.ElementClrTypeName}}> {{output.PropertyName}} => GetTensor<{{output.ElementClrTypeName}}>("{{Escape(output.OnnxName)}}");
                """;
            })
            .ToArray();

        var code = string.Join("\n\n", props);

        return $$"""
        {{_documentationPrinter.TensorCollectionType(
            summary: $"Provides typed access to the outputs produced by {specification.ClassName}.",
            tensors: specification.Outputs,
            roleLabel: "Output property"
        )}}
        public sealed class {{outputTypeName}} : IDisposable
        {
            private readonly IDisposableReadOnlyCollection<DisposableNamedOnnxValue> _results;
            private readonly Dictionary<string, DisposableNamedOnnxValue> _values;

            internal {{outputTypeName}}(IDisposableReadOnlyCollection<DisposableNamedOnnxValue> results)
            {
                if (results is null)
                {
                    throw new ArgumentNullException(nameof(results));
                }

                _results = results;
                _values = new Dictionary<string, DisposableNamedOnnxValue>(StringComparer.Ordinal);
                foreach (var value in results)
                {
                    _values[value.Name] = value;
                }
            }

            {{Indent(XmlSummary("Gets the raw ONNX Runtime outputs returned by the inference session."), 1)}}
            public IDisposableReadOnlyCollection<DisposableNamedOnnxValue> Raw => _results;
                
            {{Indent(code, 1)}}

            {{Indent(_documentationPrinter.GetTensor(), 1)}}
            public Tensor<T> GetTensor<T>(string name)
            {
                if (string.IsNullOrWhiteSpace(name))
                {
                    throw new ArgumentException("Output name must be provided.", nameof(name));
                }

                if (!_values.TryGetValue(name, out var value))
                {
                    throw new KeyNotFoundException($"The output '{name}' was not returned by the model.");
                }

                var tensor = value.AsTensor<T>();
                if (tensor is null)
                {
                    throw new InvalidOperationException($"The output '{name}' is not a tensor of the requested type {typeof(T).FullName}.");
                }

                return tensor;
            }

            {{Indent(XmlSummary("Releases the native ONNX Runtime output values for this inference result."), 1)}}
            public void Dispose()
            {
                _results.Dispose();
            }
        }
        """;
    }

    private static string BuildWrapperType(
        ModelGenerationSpecification specification,
        string inputTypeName,
        string outputTypeName
    )
    {
        var outputNames = string.Join(
            "\n",
            specification.Outputs.Select(static output => $"\"{Escape(output.OnnxName)}\","));

        var constructors = $$"""
        {{XmlSummary($"Creates a {specification.ClassName} that loads the model from DefaultModelPath.")}}
        public {{specification.ClassName}}()
            : this(DefaultModelPath, null)
        {
        }

        {{XmlSummary($"Creates a {specification.ClassName} that loads the model from DefaultModelPath.")}}
        {{XmlParam("sessionOptions", "Optional ONNX Runtime session options used when constructing the inference session.")}}
        public {{specification.ClassName}}(SessionOptions? sessionOptions)
            : this(DefaultModelPath, sessionOptions)
        {
        }

        {{XmlSummary($"Creates a {specification.ClassName} from an ONNX model file path.")}}
        {{XmlParam("modelPath", "Path to the ONNX model file to load.")}}
        public {{specification.ClassName}}(string modelPath)
            : this(modelPath, null)
        {
        }

        {{XmlSummary($"Creates a {specification.ClassName} from an ONNX model file path.")}}
        {{XmlParam("modelPath", "Path to the ONNX model file to load.")}}
        {{XmlParam("sessionOptions", "Optional ONNX Runtime session options used when constructing the inference session.")}}
        public {{specification.ClassName}}(string modelPath, SessionOptions? sessionOptions)
        {
            if (string.IsNullOrWhiteSpace(modelPath))
            {
                throw new ArgumentException("Model path must be provided.", nameof(modelPath));
            }

            Session = sessionOptions is null
                ? new InferenceSession(modelPath)
                : new InferenceSession(modelPath, sessionOptions);
        }

        {{XmlSummary($"Creates a {specification.ClassName} from the raw bytes of an ONNX model.")}}
        {{XmlParam("modelBytes", "The raw ONNX model bytes to load into the inference session.")}}
        public {{specification.ClassName}}(byte[] modelBytes)
            : this(modelBytes, null)
        {
        }

        {{XmlSummary($"Creates a {specification.ClassName} from the raw bytes of an ONNX model.")}}
        {{XmlParam("modelBytes", "The raw ONNX model bytes to load into the inference session.")}}
        {{XmlParam("sessionOptions", "Optional ONNX Runtime session options used when constructing the inference session.")}}
        public {{specification.ClassName}}(byte[] modelBytes, SessionOptions? sessionOptions)
        {
            if (modelBytes is null)
            {
                throw new ArgumentNullException(nameof(modelBytes));
            }

            Session = sessionOptions is null
                ? new InferenceSession(modelBytes)
                : new InferenceSession(modelBytes, sessionOptions);
        }
        """;

        var runMethods = specification.Inputs.Length == 0
            ? BuildParameterlessRunMethods(outputTypeName)
            : BuildInputRunMethods(specification, inputTypeName, outputTypeName);

        return $$"""
        {{XmlSummary($"Provides a typed ONNX Runtime wrapper for the model file '{specification.FileName}'.")}}
        public sealed class {{specification.ClassName}} : IDisposable
        {
            {{Indent(XmlSummary("Gets the model path relative to the consuming project directory."), 1)}}
            public const string MODEL_PROJECT_RELATIVE_PATH = {{ToVerbatimStringLiteral(specification.ProjectRelativePath)}};

            {{Indent(XmlSummary("Gets the default runtime path used to locate the ONNX model beside the application output."), 1)}}
            public static string DefaultModelPath => GetDefaultModelPath();

            {{Indent(_documentationPrinter.MetadataCollection("input", specification.Inputs), 1)}}
            public static IReadOnlyList<Onnxify.OnnxValue> Inputs { get; } = CreateInputs();

            {{Indent(_documentationPrinter.MetadataCollection("output", specification.Outputs), 1)}}
            public static IReadOnlyList<Onnxify.OnnxValue> Outputs { get; } = CreateOutputs();

            {{Indent(XmlSummary("Gets the output names requested from ONNX Runtime during inference."), 1)}}
            public static IReadOnlyList<string> OutputNames { get; } = new string[]
            {
                {{Indent(outputNames, 2)}}
            };

            {{Indent(XmlSummary("Gets the underlying ONNX Runtime inference session used by this wrapper."), 1)}}
            public InferenceSession Session { get; }

            private static IReadOnlyList<Onnxify.OnnxValue> CreateInputs()
            {
                {{Indent(BuildOnnxValueMetadata(specification.Inputs), 2)}}
            }

            private static IReadOnlyList<Onnxify.OnnxValue> CreateOutputs()
            {
                {{Indent(BuildOnnxValueMetadata(specification.Outputs), 2)}}
            }

            private static string GetDefaultModelPath()
            {
                return Path.Combine(
                    AppContext.BaseDirectory,
                    MODEL_PROJECT_RELATIVE_PATH
                        .Replace('\\', Path.DirectorySeparatorChar)
                        .Replace('/', Path.DirectorySeparatorChar)
                );
            }

            {{Indent(constructors, 1)}}

            {{Indent(runMethods, 1)}}

            {{Indent(XmlSummary("Releases the underlying ONNX Runtime inference session."), 1)}}
            public void Dispose()
            {
                Session.Dispose();
            }
        }
        """;
    }

    private static string BuildParameterlessRunMethods(string outputTypeName)
    {
        return $$"""
        {{XmlSummary("Runs inference for a model with no required inputs.")}}
        {{XmlReturns($"The typed {outputTypeName} wrapper over the ONNX Runtime outputs.")}}
        public {{outputTypeName}} Run()
        {
            return Run(null);
        }

        {{XmlSummary("Runs inference for a model with no required inputs.")}}
        {{XmlParam("runOptions", "Optional ONNX Runtime run options applied to this inference invocation.")}}
        {{XmlReturns($"The typed {outputTypeName} wrapper over the ONNX Runtime outputs.")}}
        public {{outputTypeName}} Run(RunOptions? runOptions)
        {
            var namedInputs = new List<NamedOnnxValue>(0);
            {{Indent(BuildRunInvocation(outputTypeName), 1)}}
        }
        """;
    }

    private static string BuildInputRunMethods(
        ModelGenerationSpecification specification,
        string inputTypeName,
        string outputTypeName
    )
    {
        var orderedInputs = specification.Inputs
            .OrderByDescending(static x => x.IsRequired)
            .ToArray();

        var namedInputs = string.Join(
            "\n",
            specification.Inputs.Select(static input =>
                input.IsRequired
                    ? $"namedInputs.Add(NamedOnnxValue.CreateFromTensor(\"{Escape(input.OnnxName)}\", inputs.{input.PropertyName} ?? throw new InvalidOperationException(\"Model input '{Escape(input.OnnxName)}' must be provided.\")));"
                    : $$"""
                    if (inputs.{{input.PropertyName}} is not null)
                    {
                        namedInputs.Add(NamedOnnxValue.CreateFromTensor("{{Escape(input.OnnxName)}}", inputs.{{input.PropertyName}}));
                    }
                    """));

        var signature = string.Join(", ", orderedInputs.Select(BuildTensorMethodParameterSignature));
        var signatureWithRunOptions = BuildRunMethodSignatureWithRunOptions(orderedInputs);
        var assignments = string.Join(
            "\n",
            orderedInputs.Select(static x => $"{x.PropertyName} = {x.MethodParameterName},"));

        return $$"""
        {{XmlSummary("Runs inference using the supplied input object.")}}
        {{XmlParam("inputs", $"The {inputTypeName} instance containing tensors for each required model input.")}}
        {{XmlReturns($"The typed {outputTypeName} wrapper over the ONNX Runtime outputs.")}}
        public {{outputTypeName}} Run({{inputTypeName}} inputs)
        {
            return Run(inputs, null);
        }

        {{XmlSummary("Runs inference using the supplied input object.")}}
        {{XmlParam("inputs", $"The {inputTypeName} instance containing tensors for each required model input.")}}
        {{XmlParam("runOptions", "Optional ONNX Runtime run options applied to this inference invocation.")}}
        {{XmlReturns($"The typed {outputTypeName} wrapper over the ONNX Runtime outputs.")}}
        public {{outputTypeName}} Run({{inputTypeName}} inputs, RunOptions? runOptions)
        {
            if (inputs is null)
            {
                throw new ArgumentNullException(nameof(inputs));
            }

            var namedInputs = new List<NamedOnnxValue>({{specification.Inputs.Length}});
            {{Indent(namedInputs, 1)}}

            {{Indent(BuildRunInvocation(outputTypeName), 1)}}
        }

        {{XmlSummary("Runs inference using individual tensor arguments for each model input.")}}
        {{_documentationPrinter.TensorParameters(orderedInputs)}}
        {{XmlReturns($"The typed {outputTypeName} wrapper over the ONNX Runtime outputs.")}}
        public {{outputTypeName}} Run({{signature}})
        {
            return Run(
                inputs: new {{inputTypeName}}
                {
                    {{Indent(assignments, 3)}}
                }, 
                runOptions: null
            );
        }

        {{XmlSummary("Runs inference using individual tensor arguments for each model input.")}}
        {{_documentationPrinter.TensorParameters(orderedInputs)}}
        {{XmlParam("runOptions", "Optional ONNX Runtime run options applied to this inference invocation.")}}
        {{XmlReturns($"The typed {outputTypeName} wrapper over the ONNX Runtime outputs.")}}
        public {{outputTypeName}} Run({{signatureWithRunOptions}})
        {
            return Run(
                inputs: new {{inputTypeName}}
                {
                    {{Indent(assignments, 3)}}
                }, 
                runOptions: runOptions
            );
        }
        """;
    }

    private static string BuildRunInvocation(string outputTypeName)
    {
        return $$"""
        IDisposableReadOnlyCollection<DisposableNamedOnnxValue> results;
        if (runOptions is null)
        {
            results = OutputNames.Count == 0
                ? Session.Run(namedInputs)
                : Session.Run(namedInputs, OutputNames);
        }
        else
        {
            results = Session.Run(namedInputs, OutputNames, runOptions);
        }

        return new {{outputTypeName}}(results);
        """;
    }

    private static string BuildOnnxValueMetadata(
        ImmutableArray<ModelTensorContract> tensors
    )
    {
        if (tensors.Length == 0)
        {
            return "return Array.Empty<Onnxify.OnnxValue>();";
        }

        var entries = string.Join("\n", tensors.Select(BuildOnnxValueMetadataEntry));

        return $$"""
        return new Onnxify.OnnxValue[]
        {
            {{Indent(entries, 1)}}
        };
        """;
    }

    private static string BuildOnnxValueMetadataEntry(
        ModelTensorContract tensor
    )
    {
        var tensorTypeExpression = BuildOnnxTensorTypeExpression(tensor);

        return $$"""
        new Onnxify.OnnxValue<Onnxify.OnnxTensorType>(
            name: "{{Escape(tensor.OnnxName)}}",
            type: {{Indent(tensorTypeExpression, 1)}}
        ),
        """;
    }

    private static string BuildOnnxTensorTypeExpression(ModelTensorContract tensor)
    {
        if (tensor.Shape.Any(static x => x.IsUnknown))
        {
            return $$"""
                new Onnxify.OnnxTensorType(
                    type: typeof({{tensor.ElementClrTypeName}}),
                    shape: null,
                    denotation: {{tensor.DenotationLiteral}}
                )
                """;
        }

        var dimensions = string.Join("\n", tensor.Shape.Select(BuildOnnxDimensionExpression));

        return $$"""
        Onnxify.OnnxTensorType.Create<{{tensor.ElementClrTypeName}}>(
            shape: new Onnxify.OnnxDimension[]
            {
                {{Indent(dimensions, 2)}}
            },
            denotation: {{tensor.DenotationLiteral}}
        )
        """;
    }

    private static string BuildOnnxDimensionExpression(ModelDimensionContract dimension)
    {
        if (dimension.NumericValueLiteral is not null)
        {
            return $"{dimension.NumericValueLiteral},";
        }

        if (dimension.SymbolicNameLiteral is not null)
        {
            return $"{dimension.SymbolicNameLiteral},";
        }

        throw new InvalidOperationException("Unknown ONNX dimensions cannot be expressed through the public Onnxify OnnxDimension API.");
    }

    private static string BuildTensorMethodParameterSignature(ModelTensorContract tensor)
    {
        return tensor.IsRequired
            ? $"Tensor<{tensor.ElementClrTypeName}> {tensor.MethodParameterName}"
            : $"Tensor<{tensor.ElementClrTypeName}>? {tensor.MethodParameterName} = null";
    }

    private static string BuildRunMethodSignatureWithRunOptions(
        IReadOnlyList<ModelTensorContract> orderedInputs
    )
    {
        var requiredInputs = orderedInputs
            .Where(static x => x.IsRequired)
            .Select(BuildTensorMethodParameterSignature);
        var optionalInputs = orderedInputs
            .Where(static x => !x.IsRequired)
            .Select(BuildTensorMethodParameterSignature);

        return string.Join(
            ", ",
            requiredInputs
                .Concat(["RunOptions? runOptions"])
                .Concat(optionalInputs)
        );
    }

}

