using System.Collections.Immutable;
using Onnx;
using static Onnxify.ModelGenerator.Helpers.TextHelper;
using static Onnxify.ModelGenerator.OnnxModelGenerator;

namespace Onnxify.ModelGenerator.Services;

internal sealed class TorchModulePrinter
{
    private static readonly XmlDocumentationPrinter _documentationPrinter = new();

    internal string GenerateSource(ModelGenerationSpecification specification)
    {
        var torchModule = specification.TorchModule
            ?? throw new InvalidOperationException("TorchModule generation metadata is missing.");
        var torchClassName = $"{specification.ClassName}TorchModule";

        return $$"""
        // <auto-generated/>
        #nullable enable

        using System;
        using System.Collections.Generic;
        using System.Linq;
        using TorchSharp;
        using static TorchSharp.torch;
        using static TorchSharp.torch.nn;
        using TorchModules = TorchSharp.Modules;

        namespace {{specification.NamespaceName}}
        {
            {{Indent(BuildTorchModuleType(specification, torchModule, torchClassName), 1)}}
        }

        #nullable restore
        """;
    }

    private static string BuildTorchModuleType(
        ModelGenerationSpecification specification,
        TorchModuleGenerationSpecification torchModule,
        string torchClassName
    )
    {
        var forwardGroups = BuildForwardGroups(torchModule);
        var groupedModuleNodeNames = GetGroupedModuleNodeNames(forwardGroups);
        var fields = string.Join(
            "\n",
            forwardGroups
                .Select(static group => $"private readonly {group.TypeName} {group.FieldName};")
                .Concat(torchModule.ModuleNodes
                    .Where(module => !groupedModuleNodeNames.Contains(module.NodeName))
                .Select(static module => $"private readonly {module.FieldTypeName} {module.FieldName};")
                )
                .Concat(torchModule.Initializers.Select(static initializer =>
                    $"private Tensor {initializer.FieldName};")));

        var fieldInitializers = string.Join(
            "\n",
            forwardGroups
                .Select(static group => $"{group.FieldName} = new {group.TypeName}();")
                .Concat(torchModule.ModuleNodes
                    .Where(module => !groupedModuleNodeNames.Contains(module.NodeName))
                .Select(static module => $"{module.FieldName} = {module.ConstructorExpression};")
                )
                .Concat(torchModule.Initializers.Select(static initializer =>
                    initializer.IsParameter
                        ? $$"""
                        var {{initializer.FieldName.Substring(1)}}Parameter = new global::TorchSharp.Modules.Parameter(torch.empty({{initializer.ShapeExpression}}, dtype: {{initializer.ScalarTypeExpression}}));
                        register_parameter("{{Escape(initializer.StateName)}}", {{initializer.FieldName.Substring(1)}}Parameter);
                        {{initializer.FieldName}} = {{initializer.FieldName.Substring(1)}}Parameter;
                        """
                        : $$"""
                        var {{initializer.FieldName.Substring(1)}}Buffer = torch.empty({{initializer.ShapeExpression}}, dtype: {{initializer.ScalarTypeExpression}});
                        register_buffer("{{Escape(initializer.StateName)}}", {{initializer.FieldName.Substring(1)}}Buffer);
                        {{initializer.FieldName}} = {{initializer.FieldName.Substring(1)}}Buffer;
                        """))
                .Concat(["RegisterComponents();"]));

        var loadCalls = string.Join(
            "\n",
            forwardGroups
                .Select(static group => $"{group.FieldName}.LoadWeights(tensors);")
                .Concat(torchModule.ModuleNodes
                    .Where(module => !groupedModuleNodeNames.Contains(module.NodeName))
                .SelectMany(static module => module.LoadStatements)
                )
                .Concat(torchModule.Initializers.Select(static initializer =>
                    initializer.ClrTypeName == "float"
                        ? $"LoadFloatTensor(tensors, \"{Escape(initializer.OnnxName)}\", {initializer.FieldName});"
                        : $"LoadLongTensor(tensors, \"{Escape(initializer.OnnxName)}\", {initializer.FieldName});")));

        var forwardBody = BuildTorchForwardBody(specification, torchModule, forwardGroups);
        var forwardGroupTypes = BuildForwardGroupTypes(forwardGroups, torchModule);

        return $$"""
        {{_documentationPrinter.TorchModuleType(specification)}}
        public sealed class {{torchClassName}} : torch.nn.Module<Tensor, Tensor>
        {
            {{Indent(_documentationPrinter.TorchModuleProjectRelativePath(), 1)}}
            public const string MODEL_PROJECT_RELATIVE_PATH = {{ToVerbatimStringLiteral(specification.ProjectRelativePath)}};

            {{Indent(fields, 1)}}

            {{Indent(_documentationPrinter.TorchModuleConstructor(torchClassName), 1)}}
            public {{torchClassName}}() : base(nameof({{torchClassName}}))
            {
                {{Indent(fieldInitializers, 2)}}
            }

            {{Indent(_documentationPrinter.TorchModuleLoadWeights(), 1)}}
            public void LoadWeightsFromOnnx(string modelPath)
            {
                if (string.IsNullOrWhiteSpace(modelPath))
                {
                    throw new ArgumentException("Model path must be provided.", nameof(modelPath));
                }

                var model = Onnxify.OnnxModel.FromFile(
                    modelPath,
                    new Onnxify.OnnxModelBaseOptions
                    {
                        NodeTypeResolutionStrategy = Onnxify.NodeTypeResolutionStrategy.IgnoreIncompatible,
                    }
                );

                var tensors = model.Graph.Initializers.ToDictionary(static x => x.Name, StringComparer.Ordinal);
                {{Indent(loadCalls, 2)}}
            }

            {{Indent(_documentationPrinter.TorchModuleForward(specification, torchModule), 1)}}
            public override Tensor forward(Tensor {{torchModule.InputParameterName}})
            {
                {{Indent(forwardBody, 2)}}
            }

            {{Indent(forwardGroupTypes, 1)}}

            private static Tensor CreateShapeTensor(Tensor value)
            {
                return torch.tensor(value.shape, dtype: ScalarType.Int64, device: value.device);
            }

            private static Tensor GatherTensor(Tensor input, Tensor indices, long axis)
            {
                using var flatIndices = indices.reshape(-1);
                return input.index_select(axis, flatIndices).squeeze();
            }

            private static Tensor UnsqueezeTensor(Tensor input, Tensor axes)
            {
                return UnsqueezeTensor(input, axes.data<long>().ToArray());
            }

            private static Tensor UnsqueezeTensor(Tensor input, long[] axes)
            {
                var result = input;
                foreach (var axis in axes.OrderBy(static x => x))
                {
                    result = result.unsqueeze(axis);
                }

                return result;
            }

            private static Tensor ConcatTensors(Tensor[] tensors, long axis)
            {
                if (tensors.Length == 0)
                {
                    throw new ArgumentException("At least one tensor is required.", nameof(tensors));
                }

                var device = tensors[0].device;
                var aligned = tensors.Select(x => x.device == device ? x : x.to(device)).ToArray();
                return torch.cat(aligned, axis);
            }

            private static void LoadFloatTensor(
                IReadOnlyDictionary<string, Onnxify.OnnxTensor> tensors,
                string name,
                Tensor target
            )
            {
                if (!tensors.TryGetValue(name, out var tensor))
                {
                    throw new KeyNotFoundException($"The ONNX model does not contain initializer '{name}'.");
                }

                if (tensor is not Onnxify.OnnxTensor<float> typedTensor)
                {
                    throw new InvalidOperationException($"Initializer '{name}' is not a float32 tensor.");
                }

                using var source = torch.tensor(typedTensor.Value.ToArray(), typedTensor.Shape, dtype: ScalarType.Float32, device: target.device);
                target.detach().copy_(source);
            }

            private static void LoadLongTensor(
                IReadOnlyDictionary<string, Onnxify.OnnxTensor> tensors,
                string name,
                Tensor target
            )
            {
                if (!tensors.TryGetValue(name, out var tensor))
                {
                    throw new KeyNotFoundException($"The ONNX model does not contain initializer '{name}'.");
                }

                if (tensor is not Onnxify.OnnxTensor<long> typedTensor)
                {
                    throw new InvalidOperationException($"Initializer '{name}' is not an int64 tensor.");
                }

                using var source = torch.tensor(typedTensor.Value.ToArray(), typedTensor.Shape, dtype: ScalarType.Int64, device: target.device);
                target.detach().copy_(source);
            }

            private static void LoadFloatTensorTransposed2D(
                IReadOnlyDictionary<string, Onnxify.OnnxTensor> tensors,
                string name,
                Tensor target
            )
            {
                if (!tensors.TryGetValue(name, out var tensor))
                {
                    throw new KeyNotFoundException($"The ONNX model does not contain initializer '{name}'.");
                }

                if (tensor is not Onnxify.OnnxTensor<float> typedTensor || typedTensor.Shape.Length != 2)
                {
                    throw new InvalidOperationException($"Initializer '{name}' is not a 2D float32 tensor.");
                }

                using var source = torch.tensor(typedTensor.Value.ToArray(), typedTensor.Shape, dtype: ScalarType.Float32, device: target.device).transpose(0, 1).contiguous();
                target.detach().copy_(source);
            }
        }
        """;
    }

    private static string BuildTorchForwardBody(
        ModelGenerationSpecification specification,
        TorchModuleGenerationSpecification torchModule,
        ImmutableArray<TorchForwardGroupSpecification> forwardGroups
    )
    {
        var values = new Dictionary<string, string>(StringComparer.Ordinal);
        values[torchModule.InputOnnxName] = torchModule.InputParameterName;
        foreach (var initializer in torchModule.Initializers)
        {
            values[initializer.OnnxName] = initializer.FieldName;
        }

        var statements = new List<string>();
        var modulesByNodeName = torchModule.ModuleNodes.ToDictionary(static x => x.NodeName, StringComparer.Ordinal);
        var groupsByStartNodeName = forwardGroups.ToDictionary(static x => x.Nodes[0].Name, StringComparer.Ordinal);
        var groupedNodeNames = GetGroupedTorchNodeNames(forwardGroups);

        foreach (var node in torchModule.Nodes)
        {
            if (groupedNodeNames.Contains(node.Name))
            {
                continue;
            }

            if (groupsByStartNodeName.TryGetValue(node.Name, out var group))
            {
                var input = values[group.Nodes[0].Inputs[0]];
                var groupOutput = group.OutputOnnxName;
                var groupLocalName = ToCamelIdentifier(groupOutput, "value");
                values[groupOutput] = groupLocalName;
                statements.Add($"var {groupLocalName} = {group.FieldName}.forward({input});");
                continue;
            }

            var expression = modulesByNodeName.TryGetValue(node.Name, out var module)
                ? EmitTorchModuleNode(module, node, values)
                : EmitTorchNode(node, values);
            var output = node.Outputs[0];
            var localName = ToCamelIdentifier(output, "value");
            values[output] = localName;
            statements.Add($"var {localName} = {expression};");
        }

        if (!values.TryGetValue(torchModule.OutputOnnxName, out var outputExpression))
        {
            outputExpression = ToCamelIdentifier(torchModule.OutputOnnxName, "output");
        }

        statements.Add($"return {outputExpression};");
        return string.Join("\n", statements);
    }

    private static HashSet<string> GetGroupedModuleNodeNames(
        ImmutableArray<TorchForwardGroupSpecification> forwardGroups
    )
    {
        return new HashSet<string>(
            forwardGroups
                .SelectMany(static group => group.Nodes)
                .Select(static node => node.Name),
            StringComparer.Ordinal
        );
    }

    private static HashSet<string> GetGroupedTorchNodeNames(
        ImmutableArray<TorchForwardGroupSpecification> forwardGroups
    )
    {
        return new HashSet<string>(
            forwardGroups
                .SelectMany(static group =>
                    group.ResidualAddNode is null
                        ? group.Nodes.Skip(1).Select(static node => node.Name)
                        : group.Nodes.Skip(1).Select(static node => node.Name).Concat([group.ResidualAddNode.Name])),
            StringComparer.Ordinal
        );
    }

    private static ImmutableArray<TorchForwardGroupSpecification> BuildForwardGroups(
        TorchModuleGenerationSpecification torchModule
    )
    {
        var moduleNodeNames = new HashSet<string>(
            torchModule.ModuleNodes.Select(static x => x.NodeName),
            StringComparer.Ordinal
        );

        var inputUseCounts = torchModule.Nodes
            .SelectMany(static x => x.Inputs)
            .GroupBy(static x => x, StringComparer.Ordinal)
            .ToDictionary(static x => x.Key, static x => x.Count(), StringComparer.Ordinal);

        var groups = ImmutableArray.CreateBuilder<TorchForwardGroupSpecification>();
        var index = 0;

        while (index < torchModule.Nodes.Length)
        {
            var node = torchModule.Nodes[index];
            if (!moduleNodeNames.Contains(node.Name))
            {
                index++;
                continue;
            }

            var groupNodes = ImmutableArray.CreateBuilder<TorchNodeSpecification>();
            groupNodes.Add(node);
            var cursor = index;
            while (cursor + 1 < torchModule.Nodes.Length)
            {
                var current = torchModule.Nodes[cursor];
                var next = torchModule.Nodes[cursor + 1];
                if (!moduleNodeNames.Contains(next.Name)
                    || next.Inputs.Length == 0
                    || current.Outputs.Length != 1
                    || !string.Equals(next.Inputs[0], current.Outputs[0], StringComparison.Ordinal)
                    || !inputUseCounts.TryGetValue(current.Outputs[0], out var useCount)
                    || useCount != 1)
                {
                    break;
                }

                groupNodes.Add(next);
                cursor++;
            }

            if (groupNodes.Count >= 2)
            {
                var immutableGroupNodes = groupNodes.ToImmutable();
                var residualAddNode = TryGetResidualAddNode(
                    torchModule.Nodes,
                    cursor + 1,
                    immutableGroupNodes[0].Inputs[0],
                    immutableGroupNodes[immutableGroupNodes.Length - 1].Outputs[0]
                );

                var kind = residualAddNode is null
                    ? TorchForwardGroupKind.Sequential
                    : TorchForwardGroupKind.Residual;

                var name = kind == TorchForwardGroupKind.Sequential
                    ? $"ForwardBlock{groups.Count}"
                    : $"ResidualBlock{groups.Count}";

                groups.Add(
                    new TorchForwardGroupSpecification(
                        name,
                        "_" + ToCamelIdentifier(name, "block"),
                        $"{name}Module",
                        kind,
                        immutableGroupNodes,
                        residualAddNode,
                        residualAddNode?.Outputs[0] ?? immutableGroupNodes[immutableGroupNodes.Length - 1].Outputs[0]
                    )
                );
                index = residualAddNode is null ? cursor + 1 : cursor + 2;
                continue;
            }

            index++;
        }

        return groups.ToImmutable();
    }

    private static TorchNodeSpecification? TryGetResidualAddNode(
        ImmutableArray<TorchNodeSpecification> nodes,
        int index,
        string inputName,
        string branchOutputName
    )
    {
        if (index >= nodes.Length)
        {
            return null;
        }

        var node = nodes[index];
        if (node.OpType != "Add" || node.Inputs.Length != 2)
        {
            return null;
        }

        var leftIsResidual = string.Equals(node.Inputs[0], inputName, StringComparison.Ordinal)
            && string.Equals(node.Inputs[1], branchOutputName, StringComparison.Ordinal);
        var rightIsResidual = string.Equals(node.Inputs[1], inputName, StringComparison.Ordinal)
            && string.Equals(node.Inputs[0], branchOutputName, StringComparison.Ordinal);

        return leftIsResidual || rightIsResidual ? node : null;
    }

    private static string BuildForwardGroupTypes(
        ImmutableArray<TorchForwardGroupSpecification> forwardGroups,
        TorchModuleGenerationSpecification torchModule
    )
    {
        if (forwardGroups.Length == 0)
        {
            return string.Empty;
        }

        var modulesByNodeName = torchModule.ModuleNodes.ToDictionary(static x => x.NodeName, StringComparer.Ordinal);
        return string.Join(
            "\n\n",
            forwardGroups.Select(group =>
            {
                var modules = group.Nodes.Select(node => modulesByNodeName[node.Name]).ToImmutableArray();
                var fields = string.Join(
                    "\n",
                    modules.Select(static module => $"private readonly {module.FieldTypeName} {module.FieldName};")
                );
                var initializers = string.Join(
                    "\n",
                    modules.Select(static module => $"{module.FieldName} = {module.ConstructorExpression};")
                        .Concat(["RegisterComponents();"])
                );
                var loadStatements = string.Join(
                    "\n",
                    modules.SelectMany(static module => module.LoadStatements)
                );
                var forwardStatements = new List<string>();
                var current = "input";
                foreach (var node in group.Nodes)
                {
                    var module = modulesByNodeName[node.Name];
                    var localName = ToCamelIdentifier(node.Outputs[0], "value");
                    forwardStatements.Add($"var {localName} = {module.FieldName}.forward({current});");
                    current = localName;
                }

                forwardStatements.Add(group.Kind == TorchForwardGroupKind.Residual
                    ? $"return input + {current};"
                    : $"return {current};");

                return $$"""
                private sealed class {{group.TypeName}} : torch.nn.Module<Tensor, Tensor>
                {
                    {{Indent(fields, 1)}}

                    public {{group.TypeName}}() : base(nameof({{group.TypeName}}))
                    {
                        {{Indent(initializers, 2)}}
                    }

                    public void LoadWeights(IReadOnlyDictionary<string, Onnxify.OnnxTensor> tensors)
                    {
                        {{Indent(loadStatements, 2)}}
                    }

                    public override Tensor forward(Tensor input)
                    {
                        {{Indent(string.Join("\n", forwardStatements), 2)}}
                    }
                }
                """;
            })
        );
    }

    private static string EmitTorchModuleNode(
        TorchModuleNodeSpecification module,
        TorchNodeSpecification node,
        IReadOnlyDictionary<string, string> values
    )
    {
        var input = values[node.Inputs[0]];
        return module.Kind == TorchModuleNodeKind.Linear && module.TransposeInput
            ? $"{module.FieldName}.forward({input}.transpose(0, 1))"
            : $"{module.FieldName}.forward({input})";
    }

    private static string EmitTorchNode(
        TorchNodeSpecification node,
        IReadOnlyDictionary<string, string> values
    )
    {
        string Input(int index)
        {
            if (index >= node.Inputs.Length)
            {
                throw new InvalidOperationException($"Node '{node.Name}' does not have input {index}.");
            }

            return values[node.Inputs[index]];
        }

        return node.OpType switch
        {
            "Add" => $"{Input(0)} + {Input(1)}",
            "Sub" => $"{Input(0)} - {Input(1)}",
            "Mul" => $"{Input(0)} * {Input(1)}",
            "Div" => $"{Input(0)} / {Input(1)}",
            "Relu" => $"{Input(0)}.relu()",
            "Sigmoid" => $"{Input(0)}.sigmoid()",
            "Tanh" => $"{Input(0)}.tanh()",
            "Identity" => Input(0),
            "MatMul" => $"torch.matmul({Input(0)}, {Input(1)})",
            "Gemm" => EmitTorchGemm(node, Input(0), Input(1), node.Inputs.Length > 2 ? Input(2) : null),
            "Reshape" => $"{Input(0)}.reshape({Input(1)}.data<long>().ToArray())",
            "Flatten" => $"{Input(0)}.flatten({GetLongAttribute(node, "axis", 1L)})",
            "Transpose" => $"{Input(0)}.permute({FormatLongArray(GetLongArrayAttribute(node, "perm", []))})",
            "Clip" => EmitTorchClip(node, Input(0), node.Inputs.Length > 1 ? Input(1) : null, node.Inputs.Length > 2 ? Input(2) : null),
            "Conv" => EmitTorchConv(node, Input(0), Input(1), node.Inputs.Length > 2 ? Input(2) : "null"),
            "BatchNormalization" => EmitTorchBatchNormalization(node, Input(0), Input(3), Input(4), Input(1), Input(2)),
            "GlobalAveragePool" => $"torch.nn.functional.adaptive_avg_pool2d({Input(0)}, new long[] {{ 1L, 1L }})",
            "Shape" => $"CreateShapeTensor({Input(0)})",
            "Gather" => $"GatherTensor({Input(0)}, {Input(1)}, {GetLongAttribute(node, "axis", 0L)}L)",
            "Unsqueeze" => node.Inputs.Length > 1
                ? $"UnsqueezeTensor({Input(0)}, {Input(1)})"
                : $"UnsqueezeTensor({Input(0)}, {FormatLongArray(GetLongArrayAttribute(node, "axes", []))})",
            "Concat" => $"ConcatTensors(new Tensor[] {{ {string.Join(", ", node.Inputs.Select(x => values[x]))} }}, {GetLongAttribute(node, "axis", 0L)}L)",
            "Constant" => EmitTorchConstant(node),
            _ => throw new NotSupportedException($"Unsupported TorchModule node op '{node.OpType}'."),
        };
    }

    private static string EmitTorchGemm(
        TorchNodeSpecification node,
        string a,
        string b,
        string? c
    )
    {
        var alpha = GetFloatAttribute(node, "alpha", 1f);
        var beta = GetFloatAttribute(node, "beta", 1f);
        var transA = GetLongAttribute(node, "transA", 0L) != 0;
        var transB = GetLongAttribute(node, "transB", 0L) != 0;
        var left = transA ? $"{a}.transpose(0, 1)" : a;
        var right = transB ? $"{b}.transpose(0, 1)" : b;
        var expression = $"torch.matmul({left}, {right})";

        if (alpha != 1f)
        {
            expression = $"({FormatFloat(alpha)}f * {expression})";
        }

        if (c is not null)
        {
            var bias = beta == 1f ? c : $"({FormatFloat(beta)}f * {c})";
            expression = $"({expression} + {bias})";
        }

        return expression;
    }

    private static string EmitTorchClip(
        TorchNodeSpecification node,
        string input,
        string? min,
        string? max
    )
    {
        if (min is null && node.Attributes.TryGetValue("min", out var minAttribute))
        {
            min = FormatAttributeScalar(minAttribute);
        }

        if (max is null && node.Attributes.TryGetValue("max", out var maxAttribute))
        {
            max = FormatAttributeScalar(maxAttribute);
        }

        return $"{input}.clamp({min ?? "null"}, {max ?? "null"})";
    }

    private static string EmitTorchConv(
        TorchNodeSpecification node,
        string input,
        string weight,
        string bias
    )
    {
        var strides = GetLongArrayAttribute(node, "strides", [1L, 1L]);
        var pads = GetLongArrayAttribute(node, "pads", [0L, 0L, 0L, 0L]);
        var dilations = GetLongArrayAttribute(node, "dilations", [1L, 1L]);
        var group = GetLongAttribute(node, "group", 1L);
        var padding = pads.Length >= 2 ? pads.Take(pads.Length / 2).ToArray() : pads;

        return $"torch.nn.functional.conv2d({input}, {weight}, {bias}, {FormatLongArray(strides)}, {FormatLongArray(padding)}, {FormatLongArray(dilations)}, {group}L)";
    }

    private static string EmitTorchBatchNormalization(
        TorchNodeSpecification node,
        string input,
        string runningMean,
        string runningVar,
        string weight,
        string bias
    )
    {
        var epsilon = GetFloatAttribute(node, "epsilon", 1e-5f);
        var momentum = GetFloatAttribute(node, "momentum", 0.9f);

        return $"torch.nn.functional.batch_norm({input}, {runningMean}, {runningVar}, {weight}, {bias}, training: false, momentum: {FormatFloat(momentum)}f, eps: {FormatFloat(epsilon)}f)";
    }

    private static string EmitTorchConstant(TorchNodeSpecification node)
    {
        if (!node.Attributes.TryGetValue("value", out var value) || value is not TensorProto tensor)
        {
            throw new NotSupportedException($"Constant node '{node.Name}' does not contain a tensor value attribute.");
        }

        return FormatTensorProtoExpression(tensor);
    }

}

