// <auto-generated/>
#nullable enable

using System;
using System.IO;
using Microsoft.ML.OnnxRuntime;

namespace {{OnnxifyModelNamespace}}
{
    /// <summary>
    /// Provides shared ONNX Runtime session management for generated model wrappers.
    /// </summary>
    public abstract class InferenceSessionModel : IDisposable
    {
        /// <summary>
        /// Initializes a new generated model wrapper from an ONNX model file.
        /// </summary>
        protected InferenceSessionModel(
            string modelPath,
            SessionOptions? sessionOptions
        )
        {
            if (string.IsNullOrWhiteSpace(modelPath))
            {
                throw new ArgumentException("Model path must be provided.", nameof(modelPath));
            }

            Session = sessionOptions is null
                ? new InferenceSession(modelPath: modelPath)
                : new InferenceSession(modelPath: modelPath, options: sessionOptions);
        }

        /// <summary>
        /// Initializes a new generated model wrapper from ONNX model bytes.
        /// </summary>
        protected InferenceSessionModel(
            byte[] modelBytes,
            SessionOptions? sessionOptions
        )
        {
            if (modelBytes is null)
            {
                throw new ArgumentNullException(nameof(modelBytes));
            }

            Session = sessionOptions is null
                ? new InferenceSession(model: modelBytes)
                : new InferenceSession(model: modelBytes, options: sessionOptions);
        }

        /// <summary>
        /// Gets the ONNX Runtime inference session used by the generated wrapper.
        /// </summary>
        public InferenceSession Session { get; }

        /// <summary>
        /// Resolves a generated model file path relative to the application base directory.
        /// </summary>
        protected static string GetDefaultModelPath(string projectRelativePath)
        {
            return Path.Combine(
                path1: AppContext.BaseDirectory,
                path2: projectRelativePath
                    .Replace(oldChar: '\\', newChar: Path.DirectorySeparatorChar)
                    .Replace(oldChar: '/', newChar: Path.DirectorySeparatorChar)
            );
        }

        /// <summary>
        /// Releases the ONNX Runtime inference session.
        /// </summary>
        public void Dispose()
        {
            Session.Dispose();
        }
    }
}

#nullable restore
