// <auto-generated/>
#nullable enable

using System;
using System.IO;
using Microsoft.ML.OnnxRuntime;

namespace Onnxify.Abstractions
{
    public abstract class InferenceSessionModel : IDisposable
    {
        protected InferenceSessionModel(
            string modelPath,
            SessionOptions? sessionOptions
        )
        {
            if (string.IsNullOrWhiteSpace(modelPath))
            {
                throw new ArgumentException("Model path must be provided.", nameof(modelPath));
            }

            Session = sessionOptions is null
                ? new InferenceSession(modelPath: modelPath)
                : new InferenceSession(modelPath: modelPath, options: sessionOptions);
        }

        protected InferenceSessionModel(
            byte[] modelBytes,
            SessionOptions? sessionOptions
        )
        {
            if (modelBytes is null)
            {
                throw new ArgumentNullException(nameof(modelBytes));
            }

            Session = sessionOptions is null
                ? new InferenceSession(model: modelBytes)
                : new InferenceSession(model: modelBytes, options: sessionOptions);
        }

        public InferenceSession Session { get; }

        protected static string GetDefaultModelPath(string projectRelativePath)
        {
            return Path.Combine(
                path1: AppContext.BaseDirectory,
                path2: projectRelativePath
                    .Replace(oldChar: '\\', newChar: Path.DirectorySeparatorChar)
                    .Replace(oldChar: '/', newChar: Path.DirectorySeparatorChar)
            );
        }

        public void Dispose()
        {
            Session.Dispose();
        }
    }
}

#nullable restore
