// <auto-generated/>
#nullable enable

using System;
using System.Collections.Generic;
using System.Linq;
using TorchSharp;
using static TorchSharp.torch;
using static TorchSharp.torch.nn;
using TorchModules = TorchSharp.Modules;

namespace Onnxify.Abstractions
{
    public abstract class TorchSharpModel
    {
        protected internal static Tensor CreateShapeTensor(Tensor value)
        {
            return torch.tensor(value.shape, dtype: ScalarType.Int64, device: value.device);
        }

        protected internal static Tensor GatherTensor(Tensor input, Tensor indices, long axis)
        {
            using var flatIndices = indices.reshape(-1);
            return input.index_select(axis, flatIndices).squeeze();
        }

        protected internal static Tensor UnsqueezeTensor(Tensor input, Tensor axes)
        {
            return UnsqueezeTensor(input, axes.data<long>().ToArray());
        }

        protected internal static Tensor UnsqueezeTensor(Tensor input, long[] axes)
        {
            var result = input;
            foreach (var axis in axes.OrderBy(static x => x))
            {
                result = result.unsqueeze(axis);
            }

            return result;
        }

        protected internal static Tensor SqueezeTensor(Tensor input, Tensor axes)
        {
            return SqueezeTensor(input, axes.data<long>().ToArray());
        }

        protected internal static Tensor SqueezeTensor(Tensor input, long[] axes)
        {
            if (axes.Length == 0)
            {
                return input.squeeze();
            }

            var result = input;
            foreach (var axis in NormalizeAxes(axes, input.shape.Length).OrderByDescending(static x => x))
            {
                result = result.squeeze(axis);
            }

            return result;
        }

        protected internal static Tensor ConcatTensors(Tensor[] tensors, long axis)
        {
            if (tensors.Length == 0)
            {
                throw new ArgumentException("At least one tensor is required.", nameof(tensors));
            }

            var device = tensors[0].device;
            var aligned = tensors.Select(x => x.device == device ? x : x.to(device)).ToArray();
            return torch.cat(aligned, axis);
        }

        protected internal static Tensor ScatterNdTensor(Tensor data, Tensor indices, Tensor updates, string reduction)
        {
            if (!string.Equals(reduction, "none", StringComparison.OrdinalIgnoreCase))
            {
                throw new NotSupportedException($"ScatterND reduction '{reduction}' is not supported by the generated TorchModule.");
            }

            using var cpuIndices = indices.to(ScalarType.Int64).cpu();
            var indexShape = cpuIndices.shape;
            if (indexShape.Length == 0)
            {
                throw new InvalidOperationException("ScatterND indices must have rank at least 1.");
            }

            var indexTupleLength = checked((int)indexShape[indexShape.Length - 1]);
            if (indexTupleLength <= 0 || indexTupleLength > data.shape.Length)
            {
                throw new InvalidOperationException("ScatterND index tuple length must be between 1 and the input tensor rank.");
            }

            var updateCount = indexShape.Aggregate(1L, static (product, dimension) => product * dimension) / indexTupleLength;
            var sliceSize = data.shape
                .Skip(indexTupleLength)
                .Aggregate(1L, static (product, dimension) => product * dimension);
            var dataStrides = ComputeContiguousStrides(data.shape);
            var rawIndices = cpuIndices.data<long>().ToArray();
            var flattenedOffsets = new long[checked((int)(updateCount * sliceSize))];

            for (var updateIndex = 0L; updateIndex < updateCount; updateIndex++)
            {
                var baseOffset = 0L;
                for (var tupleIndex = 0; tupleIndex < indexTupleLength; tupleIndex++)
                {
                    var dimension = data.shape[tupleIndex];
                    var index = rawIndices[checked((int)(updateIndex * indexTupleLength + tupleIndex))];
                    if (index < 0)
                    {
                        index += dimension;
                    }

                    baseOffset += index * dataStrides[tupleIndex];
                }

                for (var sliceOffset = 0L; sliceOffset < sliceSize; sliceOffset++)
                {
                    flattenedOffsets[checked((int)(updateIndex * sliceSize + sliceOffset))] = baseOffset + sliceOffset;
                }
            }

            var result = data.clone();
            using var flatResult = result.reshape(-1);
            using var offsetTensor = torch.tensor(flattenedOffsets, new long[] { flattenedOffsets.LongLength }, dtype: ScalarType.Int64, device: data.device);
            using var flatUpdates = updates.reshape(-1).to(data.device);
            flatResult.scatter_(0L, offsetTensor, flatUpdates);
            return result;
        }

        protected internal static long[] ComputeContiguousStrides(long[] shape)
        {
            var strides = new long[shape.Length];
            var stride = 1L;
            for (var index = shape.Length - 1; index >= 0; index--)
            {
                strides[index] = stride;
                stride *= shape[index];
            }

            return strides;
        }

        protected internal static Tensor MaxTensors(Tensor[] tensors)
        {
            if (tensors.Length == 0)
            {
                throw new ArgumentException("At least one tensor is required.", nameof(tensors));
            }

            var result = tensors[0];
            foreach (var tensor in tensors.Skip(1))
            {
                result = torch.maximum(result, tensor);
            }

            return result;
        }

        protected internal static Tensor MinTensors(Tensor[] tensors)
        {
            if (tensors.Length == 0)
            {
                throw new ArgumentException("At least one tensor is required.", nameof(tensors));
            }

            var result = tensors[0];
            foreach (var tensor in tensors.Skip(1))
            {
                result = torch.minimum(result, tensor);
            }

            return result;
        }

        protected internal static Tensor ModTensor(Tensor input, Tensor other, bool fmod)
        {
            return fmod ? input.fmod(other) : input.remainder(other);
        }

        protected internal static Tensor IsInfTensor(Tensor input, long detectNegative, long detectPositive)
        {
            var isInf = input.isinf();
            if (detectNegative != 0L && detectPositive != 0L)
            {
                return isInf;
            }

            var zero = torch.zeros(Array.Empty<long>(), dtype: input.dtype, device: input.device);
            if (detectNegative != 0L)
            {
                return input.lt(zero).logical_and(isInf);
            }

            if (detectPositive != 0L)
            {
                return input.gt(zero).logical_and(isInf);
            }

            return torch.zeros_like(isInf);
        }

        protected internal static Tensor BitwiseNotTensor(Tensor input)
        {
            return input.dtype == ScalarType.Bool ? input.logical_not() : input.bitwise_not();
        }

        protected internal static Tensor BitwiseAndTensor(Tensor input, Tensor other)
        {
            return input.dtype == ScalarType.Bool && other.dtype == ScalarType.Bool
                ? input.logical_and(other)
                : input.bitwise_and(other);
        }

        protected internal static Tensor BitwiseOrTensor(Tensor input, Tensor other)
        {
            return input.dtype == ScalarType.Bool && other.dtype == ScalarType.Bool
                ? input.logical_or(other)
                : input.bitwise_or(other);
        }

        protected internal static Tensor BitwiseXorTensor(Tensor input, Tensor other)
        {
            return input.dtype == ScalarType.Bool && other.dtype == ScalarType.Bool
                ? input.logical_xor(other)
                : input.bitwise_xor(other);
        }

        protected internal static Tensor ReduceMeanTensor(Tensor input, Tensor? axes, bool keepDims)
        {
            return ReduceMeanTensor(input, axes?.data<long>().ToArray(), keepDims);
        }

        protected internal static Tensor ReduceMeanTensor(Tensor input, long[]? axes, bool keepDims)
        {
            return input.mean(ResolveReductionAxes(axes, input.shape.Length), keepDims);
        }

        protected internal static Tensor ReduceSumTensor(Tensor input, Tensor? axes, bool keepDims)
        {
            return ReduceSumTensor(input, axes?.data<long>().ToArray(), keepDims);
        }

        protected internal static Tensor ReduceSumTensor(Tensor input, long[]? axes, bool keepDims)
        {
            return input.sum(ResolveReductionAxes(axes, input.shape.Length), keepDims);
        }

        protected internal static Tensor ReduceMaxTensor(Tensor input, Tensor? axes, bool keepDims)
        {
            return ReduceMaxTensor(input, axes?.data<long>().ToArray(), keepDims);
        }

        protected internal static Tensor ReduceMaxTensor(Tensor input, long[]? axes, bool keepDims)
        {
            var resolvedAxes = ResolveReductionAxes(axes, input.shape.Length);
            var result = input;
            foreach (var axis in resolvedAxes.OrderByDescending(static x => x))
            {
                result = result.max(axis, keepdim: keepDims).values;
            }

            return result;
        }

        protected internal static Tensor ReduceMinTensor(Tensor input, Tensor? axes, bool keepDims)
        {
            return ReduceMinTensor(input, axes?.data<long>().ToArray(), keepDims);
        }

        protected internal static Tensor ReduceMinTensor(Tensor input, long[]? axes, bool keepDims)
        {
            var resolvedAxes = ResolveReductionAxes(axes, input.shape.Length);
            var result = input;
            foreach (var axis in resolvedAxes.OrderByDescending(static x => x))
            {
                result = result.min(axis, keepdim: keepDims).values;
            }

            return result;
        }

        protected internal static Tensor ReduceProdTensor(Tensor input, Tensor? axes, bool keepDims)
        {
            return ReduceProdTensor(input, axes?.data<long>().ToArray(), keepDims);
        }

        protected internal static Tensor ReduceProdTensor(Tensor input, long[]? axes, bool keepDims)
        {
            var resolvedAxes = ResolveReductionAxes(axes, input.shape.Length);
            var result = input;
            foreach (var axis in resolvedAxes.OrderByDescending(static x => x))
            {
                result = result.prod(axis, keepdim: keepDims);
            }

            return result;
        }

        protected internal static Tensor ReduceL1Tensor(Tensor input, Tensor? axes, bool keepDims)
        {
            return ReduceL1Tensor(input, axes?.data<long>().ToArray(), keepDims);
        }

        protected internal static Tensor ReduceL1Tensor(Tensor input, long[]? axes, bool keepDims)
        {
            return input.abs().sum(ResolveReductionAxes(axes, input.shape.Length), keepDims);
        }

        protected internal static Tensor ReduceL2Tensor(Tensor input, Tensor? axes, bool keepDims)
        {
            return ReduceL2Tensor(input, axes?.data<long>().ToArray(), keepDims);
        }

        protected internal static Tensor ReduceL2Tensor(Tensor input, long[]? axes, bool keepDims)
        {
            return input.pow(2).sum(ResolveReductionAxes(axes, input.shape.Length), keepDims).sqrt();
        }

        protected internal static Tensor ReduceLogSumExpTensor(Tensor input, Tensor? axes, bool keepDims)
        {
            return ReduceLogSumExpTensor(input, axes?.data<long>().ToArray(), keepDims);
        }

        protected internal static Tensor ReduceLogSumExpTensor(Tensor input, long[]? axes, bool keepDims)
        {
            return input.exp().sum(ResolveReductionAxes(axes, input.shape.Length), keepDims).log();
        }

        protected internal static long[] ResolveReductionAxes(long[]? axes, int rank)
        {
            return axes is null || axes.Length == 0
                ? Enumerable.Range(0, rank).Select(static x => (long)x).ToArray()
                : NormalizeAxes(axes, rank);
        }

        protected internal static long[] NormalizeAxes(long[] axes, int rank)
        {
            return axes
                .Select(axis => axis < 0 ? axis + rank : axis)
                .ToArray();
        }

        protected internal static Tensor CumSumTensor(Tensor input, Tensor axis, bool reverse, bool exclusive)
        {
            var dim = axis.data<long>().ToArray()[0];
            var source = reverse ? input.flip(new long[] { dim }) : input;
            var result = source.cumsum(dim);
            if (exclusive)
            {
                result = result - source;
            }

            return reverse ? result.flip(new long[] { dim }) : result;
        }

        protected internal static Tensor DepthToSpaceTensor(Tensor input, long blockSize, string mode)
        {
            var shape = input.shape;
            if (shape.Length != 4)
            {
                throw new InvalidOperationException("DepthToSpace expects a rank-4 tensor.");
            }

            var n = shape[0];
            var c = shape[1] / (blockSize * blockSize);
            var h = shape[2];
            var w = shape[3];
            return string.Equals(mode, "CRD", StringComparison.OrdinalIgnoreCase)
                ? input.reshape(new long[] { n, c, blockSize, blockSize, h, w }).permute(0, 1, 4, 2, 5, 3).reshape(new long[] { n, c, h * blockSize, w * blockSize })
                : input.reshape(new long[] { n, blockSize, blockSize, c, h, w }).permute(0, 3, 4, 1, 5, 2).reshape(new long[] { n, c, h * blockSize, w * blockSize });
        }

        protected internal static Tensor SpaceToDepthTensor(Tensor input, long blockSize)
        {
            var shape = input.shape;
            if (shape.Length != 4)
            {
                throw new InvalidOperationException("SpaceToDepth expects a rank-4 tensor.");
            }

            var n = shape[0];
            var c = shape[1];
            var h = shape[2] / blockSize;
            var w = shape[3] / blockSize;
            return input.reshape(new long[] { n, c, h, blockSize, w, blockSize }).permute(0, 3, 5, 1, 2, 4).reshape(new long[] { n, c * blockSize * blockSize, h, w });
        }

        protected internal static Tensor LayerNormTensor(Tensor input, Tensor scale, Tensor? bias, long axis, float epsilon)
        {
            var rank = input.shape.Length;
            var normalizedAxis = axis < 0 ? axis + rank : axis;
            var normalizedShape = input.shape.Skip(checked((int)normalizedAxis)).ToArray();
            return torch.nn.functional.layer_norm(input, normalizedShape, scale, bias, eps: epsilon);
        }

        protected internal static Tensor SimplifiedLayerNormTensor(Tensor input, Tensor scale, Tensor? bias, long axis, float epsilon)
        {
            var rank = input.shape.Length;
            var normalizedAxis = axis < 0 ? axis + rank : axis;
            var axes = Enumerable
                .Range(checked((int)normalizedAxis), rank - checked((int)normalizedAxis))
                .Select(static x => (long)x)
                .ToArray();
            var rms = (input.pow(2).mean(axes, keepdim: true) + epsilon).sqrt();
            var result = input / rms * scale;
            return bias is null ? result : result + bias;
        }

        protected internal static Tensor PadTensor(Tensor input, Tensor pads, Tensor? constantValue, string mode)
        {
            var rawPads = pads.data<long>().ToArray();
            var rank = rawPads.Length / 2;
            var torchPads = new List<long>(rawPads.Length);
            for (var axis = rank - 1; axis >= 0; axis--)
            {
                torchPads.Add(rawPads[axis]);
                torchPads.Add(rawPads[axis + rank]);
            }

            var value = constantValue is null ? 0.0 : Convert.ToDouble(constantValue.cpu().item<double>());
            return torch.nn.functional.pad(input, torchPads.ToArray(), mode: ParsePaddingMode(mode), value: value);
        }

        protected internal static PaddingModes ParsePaddingMode(string mode)
        {
            return mode switch
            {
                "constant" => PaddingModes.Constant,
                "reflect" => PaddingModes.Reflect,
                "replicate" => PaddingModes.Replicate,
                "edge" => PaddingModes.Replicate,
                "circular" => PaddingModes.Circular,
                _ => throw new NotSupportedException($"Unsupported Pad mode '{mode}'."),
            };
        }

        protected internal static Tensor SliceTensor(Tensor input, Tensor starts, Tensor ends, Tensor? axes, Tensor? steps)
        {
            var result = input;
            var startValues = starts.data<long>().ToArray();
            var endValues = ends.data<long>().ToArray();
            var axisValues = axes?.data<long>().ToArray() ?? Enumerable.Range(0, startValues.Length).Select(static x => (long)x).ToArray();
            var stepValues = steps?.data<long>().ToArray() ?? Enumerable.Repeat(1L, startValues.Length).ToArray();
            for (var i = 0; i < startValues.Length; i++)
            {
                var axis = axisValues[i] < 0 ? axisValues[i] + result.shape.Length : axisValues[i];
                var dim = result.shape[axis];
                var start = startValues[i] < 0 ? startValues[i] + dim : startValues[i];
                var end = endValues[i] < 0 ? endValues[i] + dim : Math.Min(endValues[i], dim);
                var step = stepValues[i];
                if (step == 1L)
                {
                    result = result.narrow((int)axis, (int)start, Math.Max(0L, end - start));
                }
                else
                {
                    using var indices = torch.arange((int)start, (int)end, (int)step, dtype: ScalarType.Int64, device: input.device);
                    result = result.index_select((int)axis, indices);
                }
            }

            return result;
        }

        protected internal static Tensor[] SplitTensor(Tensor input, Tensor? split, long axis, long outputCount)
        {
            var axisIndex = (int)axis;
            var splitSizes = split?.data<long>().ToArray();
            if (splitSizes is null)
            {
                var size = input.shape[axis] / outputCount;
                splitSizes = Enumerable.Repeat(size, checked((int)outputCount)).ToArray();
            }

            var result = new Tensor[splitSizes.Length];
            var offset = 0L;
            for (var i = 0; i < splitSizes.Length; i++)
            {
                result[i] = input.narrow(axisIndex, (int)offset, splitSizes[i]);
                offset += splitSizes[i];
            }

            return result;
        }

        protected internal static Tensor[] TopKTensor(Tensor input, Tensor k, long axis, bool largest, bool sorted)
        {
            var kValue = k.data<long>().ToArray()[0];
            var result = input.topk((int)kValue, dim: (int)axis, largest: largest, sorted: sorted);
            return new Tensor[] { result.values, result.indexes };
        }

        protected internal static Tensor TriluTensor(Tensor input, Tensor? k, bool upper)
        {
            var diagonal = k is null ? 0L : k.data<long>().ToArray()[0];
            return upper ? input.triu((int)diagonal) : input.tril((int)diagonal);
        }

        protected internal static Tensor ResizeTensor(Tensor input, Tensor? scales, Tensor? sizes, string mode, string coordinateTransformationMode)
        {
            if (coordinateTransformationMode is not ("asymmetric" or "half_pixel" or "pytorch_half_pixel"))
            {
                throw new NotSupportedException($"Unsupported Resize coordinate_transformation_mode '{coordinateTransformationMode}'.");
            }

            var interpolationMode = mode switch
            {
                "nearest" => global::TorchSharp.torch.InterpolationMode.Nearest,
                "linear" => input.shape.Length switch
                {
                    3 => global::TorchSharp.torch.InterpolationMode.Linear,
                    4 => global::TorchSharp.torch.InterpolationMode.Bilinear,
                    5 => global::TorchSharp.torch.InterpolationMode.Trilinear,
                    _ => throw new NotSupportedException($"Resize linear mode requires rank 3, 4, or 5 input. Got rank {input.shape.Length}."),
                },
                "cubic" => global::TorchSharp.torch.InterpolationMode.Bicubic,
                _ => throw new NotSupportedException($"Unsupported Resize mode '{mode}'."),
            };

            long[] outputSpatialSizes = [];
            double[] outputSpatialScales = [];
            if (sizes is not null)
            {
                var rawSizes = sizes.data<long>().ToArray();
                outputSpatialSizes = rawSizes.Length == input.shape.Length
                    ? rawSizes.Skip(2).ToArray()
                    : rawSizes;
            }
            else if (scales is not null)
            {
                var rawScales = scales.to(ScalarType.Float64).data<double>().ToArray();
                outputSpatialScales = rawScales.Length == input.shape.Length
                    ? rawScales.Skip(2).ToArray()
                    : rawScales;
            }
            else
            {
                throw new InvalidOperationException("Resize requires either scales or sizes.");
            }

            bool? alignCorners = coordinateTransformationMode == "pytorch_half_pixel" && (mode is "linear" or "cubic")
                ? false
                : null;
            return torch.nn.functional.interpolate(
                input,
                outputSpatialSizes,
                outputSpatialScales,
                interpolationMode,
                align_corners: alignCorners,
                recompute_scale_factor: false,
                antialias: false
            );
        }

        protected internal static Tensor ToOnnxLstmY(Tensor torchY, long numDirections, long hiddenSize)
        {
            var shape = torchY.shape;
            if (shape.Length != 3)
            {
                throw new InvalidOperationException($"TorchSharp LSTM output must have rank 3. Got rank {shape.Length}.");
            }

            return torchY
                .reshape(new long[] { shape[0], shape[1], numDirections, hiddenSize })
                .permute(0, 2, 1, 3);
        }

        protected internal static Tensor[] ToOnnxGruOutputs((Tensor, Tensor) torchOutput, long numDirections, long hiddenSize)
        {
            var y = ToOnnxGruY(torchOutput.Item1, numDirections, hiddenSize);
            return new Tensor[] { y, torchOutput.Item2 };
        }

        protected internal static Tensor ToOnnxGruY(Tensor torchY, long numDirections, long hiddenSize)
        {
            var shape = torchY.shape;
            if (shape.Length != 3)
            {
                throw new InvalidOperationException($"TorchSharp GRU output must have rank 3. Got rank {shape.Length}.");
            }

            return torchY
                .reshape(new long[] { shape[0], shape[1], numDirections, hiddenSize })
                .permute(0, 2, 1, 3);
        }

        protected internal static Tensor QuantizeLinearTensor(Tensor input, Tensor scale, Tensor? zeroPoint, long axis)
        {
            var alignedScale = AlignQuantizationParameter(scale, input, axis);
            var scaled = input / alignedScale;
            var shifted = zeroPoint is null
                ? scaled
                : scaled + AlignQuantizationParameter(zeroPoint, input, axis).to(ScalarType.Float32);
            var rounded = shifted.round();
            return (zeroPoint?.dtype ?? ScalarType.Byte) switch
            {
                ScalarType.Byte => rounded.clamp(0, 255).to(ScalarType.Byte),
                ScalarType.Int8 => rounded.clamp(-128, 127).to(ScalarType.Int8),
                ScalarType.Int32 => rounded.to(ScalarType.Int32),
                _ => throw new NotSupportedException($"Unsupported QuantizeLinear zero-point tensor data type: {zeroPoint!.dtype}."),
            };
        }

        protected internal static Tensor DequantizeLinearTensor(Tensor input, Tensor scale, Tensor? zeroPoint, long axis)
        {
            var alignedScale = AlignQuantizationParameter(scale, input, axis);
            var shifted = zeroPoint is null
                ? input.to(ScalarType.Float32)
                : input.to(ScalarType.Float32) - AlignQuantizationParameter(zeroPoint, input, axis).to(ScalarType.Float32);
            return shifted * alignedScale;
        }

        protected internal static Tensor AlignQuantizationParameter(Tensor parameter, Tensor input, long axis)
        {
            var parameterShape = parameter.shape;
            if (parameterShape.Length == 0 || parameterShape.Aggregate(1L, static (product, dim) => product * dim) == 1L)
            {
                return parameter;
            }

            var inputRank = input.shape.Length;
            var normalizedAxis = axis < 0 ? axis + inputRank : axis;
            if (normalizedAxis < 0 || normalizedAxis >= inputRank)
            {
                throw new ArgumentOutOfRangeException(nameof(axis), axis, "Quantization axis is outside the input tensor rank.");
            }

            var shape = Enumerable.Repeat(1L, inputRank).ToArray();
            shape[normalizedAxis] = parameterShape[0];
            return parameter.reshape(shape);
        }

        protected internal sealed class OnnxInitializerLookup
        {
            private readonly IReadOnlyList<Onnxify.OnnxTensor> _byIndex;
            private readonly IReadOnlyDictionary<string, Onnxify.OnnxTensor> _byName;

            public OnnxInitializerLookup(IReadOnlyList<Onnxify.OnnxTensor> initializers)
            {
                _byIndex = initializers;
                _byName = initializers.ToDictionary(static x => x.Name, StringComparer.Ordinal);
            }

            public bool TryGetByName(string name, out Onnxify.OnnxTensor tensor)
            {
                return _byName.TryGetValue(name, out tensor!);
            }

            public bool TryGetByIndex(int index, out Onnxify.OnnxTensor tensor)
            {
                if (index >= 0 && index < _byIndex.Count)
                {
                    tensor = _byIndex[index];
                    return true;
                }

                tensor = null!;
                return false;
            }
        }

        protected internal static void LoadFloatTensor(
            OnnxInitializerLookup tensors,
            string name,
            int canonicalIndex,
            long[] expectedShape,
            Tensor target
        )
        {
            var typedTensor = GetTensor<float>(tensors, name, canonicalIndex, expectedShape, "float32");

            using var source = torch.tensor(typedTensor.Value.ToArray(), typedTensor.Shape, dtype: ScalarType.Float32, device: target.device);
            target.detach().copy_(source);
        }

        protected internal static void LoadLongTensor(
            OnnxInitializerLookup tensors,
            string name,
            int canonicalIndex,
            long[] expectedShape,
            Tensor target
        )
        {
            var typedTensor = GetTensor<long>(tensors, name, canonicalIndex, expectedShape, "int64");

            using var source = torch.tensor(typedTensor.Value.ToArray(), typedTensor.Shape, dtype: ScalarType.Int64, device: target.device);
            target.detach().copy_(source);
        }

        protected internal static void LoadTensor<T>(
            OnnxInitializerLookup tensors,
            string name,
            int canonicalIndex,
            long[] expectedShape,
            Tensor target,
            ScalarType scalarType
        )
        {
            if (scalarType == ScalarType.BFloat16)
            {
                LoadBFloat16Tensor(tensors, name, canonicalIndex, expectedShape, target);
                return;
            }

            var typedTensor = GetTensor<T>(tensors, name, canonicalIndex, expectedShape, typeof(T).Name);

            var values = typedTensor.Value.ToArray();
            using var source = scalarType switch
            {
                ScalarType.Byte => torch.tensor((byte[])(object)values, typedTensor.Shape, dtype: ScalarType.Byte, device: target.device),
                ScalarType.Int8 => torch.tensor((sbyte[])(object)values, typedTensor.Shape, dtype: ScalarType.Int8, device: target.device),
                ScalarType.Int16 => torch.tensor((short[])(object)values, typedTensor.Shape, dtype: ScalarType.Int16, device: target.device),
                ScalarType.Int32 => torch.tensor((int[])(object)values, typedTensor.Shape, dtype: ScalarType.Int32, device: target.device),
                ScalarType.Int64 => torch.tensor((long[])(object)values, typedTensor.Shape, dtype: ScalarType.Int64, device: target.device),
                ScalarType.Float16 => torch.tensor(((Half[])(object)values).Select(static x => (float)x).ToArray(), typedTensor.Shape, dtype: ScalarType.Float16, device: target.device),
                ScalarType.Float32 => torch.tensor((float[])(object)values, typedTensor.Shape, dtype: ScalarType.Float32, device: target.device),
                ScalarType.Float64 => torch.tensor((double[])(object)values, typedTensor.Shape, dtype: ScalarType.Float64, device: target.device),
                ScalarType.Bool => torch.tensor((bool[])(object)values, typedTensor.Shape, dtype: ScalarType.Bool, device: target.device),
                _ => throw new NotSupportedException($"Unsupported Torch tensor data type for ONNX initializer import: {scalarType}."),
            };
            target.detach().copy_(source);
        }

        protected internal static void LoadBFloat16Tensor(
            OnnxInitializerLookup tensors,
            string name,
            int canonicalIndex,
            long[] expectedShape,
            Tensor target
        )
        {
            var tensor = GetTensor(tensors, name, canonicalIndex, expectedShape, "bfloat16");
            var valueProperty = tensor.GetType().GetProperty("Value")
                ?? throw new InvalidOperationException($"Initializer '{name}' does not expose tensor values.");
            if (valueProperty.GetValue(tensor) is not System.Collections.IEnumerable values)
            {
                throw new InvalidOperationException($"Initializer '{name}' does not expose enumerable tensor values.");
            }

            var floats = new List<float>();
            foreach (var value in values)
            {
                if (value is global::TorchSharp.BFloat16 torchBFloat16)
                {
                    floats.Add(torchBFloat16.ToSingle());
                    continue;
                }

                var toSingle = value?.GetType().GetMethod("ToSingle", Type.EmptyTypes)
                    ?? throw new InvalidOperationException($"Initializer '{name}' contains unsupported bfloat16 value type '{value?.GetType().FullName ?? "<null>"}'.");
                floats.Add((float)(toSingle.Invoke(value, null) ?? throw new InvalidOperationException($"Initializer '{name}' bfloat16 value conversion returned null.")));
            }

            using var source = torch.tensor(floats.ToArray(), tensor.Shape, dtype: ScalarType.BFloat16, device: target.device);
            target.detach().copy_(source);
        }

        protected internal static void LoadFloatTensorTransposed2D(
            OnnxInitializerLookup tensors,
            string name,
            int canonicalIndex,
            long[] expectedShape,
            Tensor target
        )
        {
            var typedTensor = GetTensor<float>(tensors, name, canonicalIndex, expectedShape, "float32");
            if (typedTensor.Shape.Length != 2)
            {
                throw new InvalidOperationException($"Initializer '{name}' is not a 2D float32 tensor.");
            }

            using var source = torch.tensor(typedTensor.Value.ToArray(), typedTensor.Shape, dtype: ScalarType.Float32, device: target.device).transpose(0, 1).contiguous();
            target.detach().copy_(source);
        }

        protected internal static void LoadOnnxLstmWeights(
            OnnxInitializerLookup tensors,
            string wName,
            int wIndex,
            long[] wShape,
            string rName,
            int rIndex,
            long[] rShape,
            string? bName,
            int bIndex,
            long[]? bShape,
            TorchModules.LSTM module,
            long hiddenSize,
            long inputSize,
            long numDirections
        )
        {
            var w = GetTensor<float>(tensors, wName, wIndex, wShape, "float32");
            var r = GetTensor<float>(tensors, rName, rIndex, rShape, "float32");
            var b = bName is null || bShape is null ? null : GetTensor<float>(tensors, bName, bIndex, bShape, "float32");
            var state = module.state_dict();

            for (var direction = 0L; direction < numDirections; direction++)
            {
                var suffix = direction == 1L ? "_reverse" : string.Empty;
                CopyOnnxLstmGateMatrix(
                    w,
                    direction,
                    hiddenSize,
                    inputSize,
                    GetRequiredStateTensor(state, $"weight_ih_l0{suffix}")
                );
                CopyOnnxLstmGateMatrix(
                    r,
                    direction,
                    hiddenSize,
                    hiddenSize,
                    GetRequiredStateTensor(state, $"weight_hh_l0{suffix}")
                );

                if (b is not null)
                {
                    CopyOnnxLstmGateVector(
                        b,
                        direction,
                        hiddenSize,
                        offset: 0L,
                        GetRequiredStateTensor(state, $"bias_ih_l0{suffix}")
                    );
                    CopyOnnxLstmGateVector(
                        b,
                        direction,
                        hiddenSize,
                        offset: 4L * hiddenSize,
                        GetRequiredStateTensor(state, $"bias_hh_l0{suffix}")
                    );
                }
            }
        }

        protected internal static void LoadOnnxGruWeights(
            OnnxInitializerLookup tensors,
            string wName,
            int wIndex,
            long[] wShape,
            string rName,
            int rIndex,
            long[] rShape,
            string? bName,
            int bIndex,
            long[]? bShape,
            TorchModules.GRU module,
            long hiddenSize,
            long inputSize,
            long numDirections
        )
        {
            var w = GetTensor<float>(tensors, wName, wIndex, wShape, "float32");
            var r = GetTensor<float>(tensors, rName, rIndex, rShape, "float32");
            var b = bName is null || bShape is null ? null : GetTensor<float>(tensors, bName, bIndex, bShape, "float32");
            var state = module.state_dict();

            for (var direction = 0L; direction < numDirections; direction++)
            {
                var suffix = direction == 1L ? "_reverse" : string.Empty;
                CopyOnnxGruGateMatrix(
                    w,
                    direction,
                    hiddenSize,
                    inputSize,
                    GetRequiredStateTensor(state, $"weight_ih_l0{suffix}")
                );
                CopyOnnxGruGateMatrix(
                    r,
                    direction,
                    hiddenSize,
                    hiddenSize,
                    GetRequiredStateTensor(state, $"weight_hh_l0{suffix}")
                );

                if (b is not null)
                {
                    CopyOnnxGruGateVector(
                        b,
                        direction,
                        hiddenSize,
                        offset: 0L,
                        GetRequiredStateTensor(state, $"bias_ih_l0{suffix}")
                    );
                    CopyOnnxGruGateVector(
                        b,
                        direction,
                        hiddenSize,
                        offset: 3L * hiddenSize,
                        GetRequiredStateTensor(state, $"bias_hh_l0{suffix}")
                    );
                }
            }
        }

        protected internal static Onnxify.OnnxTensor<T> GetTensor<T>(
            OnnxInitializerLookup tensors,
            string name,
            int canonicalIndex,
            long[] expectedShape,
            string expectedTypeName
        )
        {
            if (tensors.TryGetByName(name, out var namedTensor))
            {
                return RequireTensor<T>(namedTensor, name, expectedShape, expectedTypeName);
            }

            if (tensors.TryGetByIndex(canonicalIndex, out var indexedTensor))
            {
                return RequireTensor<T>(indexedTensor, $"initializer at canonical index {canonicalIndex}", expectedShape, expectedTypeName);
            }

            throw new KeyNotFoundException($"The ONNX model does not contain initializer '{name}' and has no initializer at canonical index {canonicalIndex}.");
        }

        protected internal static Onnxify.OnnxTensor<T> RequireTensor<T>(
            Onnxify.OnnxTensor tensor,
            string label,
            long[] expectedShape,
            string expectedTypeName
        )
        {
            if (tensor is not Onnxify.OnnxTensor<T> typedTensor)
            {
                throw new InvalidOperationException($"Initializer '{label}' is not a {expectedTypeName} tensor.");
            }

            if (!typedTensor.Shape.SequenceEqual(expectedShape))
            {
                throw new InvalidOperationException($"Initializer '{label}' shape [{string.Join(", ", typedTensor.Shape)}] does not match expected shape [{string.Join(", ", expectedShape)}].");
            }

            return typedTensor;
        }

        protected internal static Onnxify.OnnxTensor GetTensor(
            OnnxInitializerLookup tensors,
            string name,
            int canonicalIndex,
            long[] expectedShape,
            string expectedTypeName
        )
        {
            if (tensors.TryGetByName(name, out var namedTensor))
            {
                return RequireTensor(namedTensor, name, expectedShape, expectedTypeName);
            }

            if (tensors.TryGetByIndex(canonicalIndex, out var indexedTensor))
            {
                return RequireTensor(indexedTensor, $"initializer at canonical index {canonicalIndex}", expectedShape, expectedTypeName);
            }

            throw new KeyNotFoundException($"The ONNX model does not contain initializer '{name}' and has no initializer at canonical index {canonicalIndex}.");
        }

        protected internal static Onnxify.OnnxTensor RequireTensor(
            Onnxify.OnnxTensor tensor,
            string label,
            long[] expectedShape,
            string expectedTypeName
        )
        {
            var dataTypeName = tensor.DataType.FullName ?? tensor.DataType.Name;
            if (expectedTypeName == "bfloat16"
                && dataTypeName != "Onnxify.Data.Numerics.BFloat16"
                && dataTypeName != "TorchSharp.BFloat16")
            {
                throw new InvalidOperationException($"Initializer '{label}' is not a {expectedTypeName} tensor.");
            }

            if (!tensor.Shape.SequenceEqual(expectedShape))
            {
                throw new InvalidOperationException($"Initializer '{label}' shape [{string.Join(", ", tensor.Shape)}] does not match expected shape [{string.Join(", ", expectedShape)}].");
            }

            return tensor;
        }

        protected internal static Tensor GetRequiredStateTensor(
            IReadOnlyDictionary<string, Tensor> state,
            string name
        )
        {
            if (!state.TryGetValue(name, out var tensor) || tensor is null || tensor.IsInvalid)
            {
                throw new KeyNotFoundException($"The TorchSharp LSTM state does not contain tensor '{name}'.");
            }

            return tensor;
        }

        protected internal static void CopyOnnxLstmGateMatrix(
            Onnxify.OnnxTensor<float> source,
            long direction,
            long hiddenSize,
            long width,
            Tensor target
        )
        {
            var data = source.Value.ToArray();
            var gateBlockLength = hiddenSize * width;
            var reordered = ReorderOnnxLstmGateData(
                data,
                direction,
                gateBlockLength,
                directionStride: 4L * gateBlockLength,
                offset: 0L
            );
            using var tensor = torch.tensor(reordered, new long[] { 4L * hiddenSize, width }, dtype: ScalarType.Float32, device: target.device);
            target.detach().copy_(tensor);
        }

        protected internal static void CopyOnnxLstmGateVector(
            Onnxify.OnnxTensor<float> source,
            long direction,
            long hiddenSize,
            long offset,
            Tensor target
        )
        {
            var data = source.Value.ToArray();
            var reordered = ReorderOnnxLstmGateData(
                data,
                direction,
                gateBlockLength: hiddenSize,
                directionStride: 8L * hiddenSize,
                offset
            );
            using var tensor = torch.tensor(reordered, new long[] { 4L * hiddenSize }, dtype: ScalarType.Float32, device: target.device);
            target.detach().copy_(tensor);
        }

        protected internal static void CopyOnnxGruGateMatrix(
            Onnxify.OnnxTensor<float> source,
            long direction,
            long hiddenSize,
            long width,
            Tensor target
        )
        {
            var data = source.Value.ToArray();
            var gateBlockLength = hiddenSize * width;
            var reordered = ReorderOnnxGruGateData(
                data,
                direction,
                gateBlockLength,
                directionStride: 3L * gateBlockLength,
                offset: 0L
            );
            using var tensor = torch.tensor(reordered, new long[] { 3L * hiddenSize, width }, dtype: ScalarType.Float32, device: target.device);
            target.detach().copy_(tensor);
        }

        protected internal static void CopyOnnxGruGateVector(
            Onnxify.OnnxTensor<float> source,
            long direction,
            long hiddenSize,
            long offset,
            Tensor target
        )
        {
            var data = source.Value.ToArray();
            var reordered = ReorderOnnxGruGateData(
                data,
                direction,
                gateBlockLength: hiddenSize,
                directionStride: 6L * hiddenSize,
                offset
            );
            using var tensor = torch.tensor(reordered, new long[] { 3L * hiddenSize }, dtype: ScalarType.Float32, device: target.device);
            target.detach().copy_(tensor);
        }

        protected internal static float[] ReorderOnnxLstmGateData(
            float[] source,
            long direction,
            long gateBlockLength,
            long directionStride,
            long offset
        )
        {
            var directionOffset = (direction * directionStride) + offset;
            var result = new float[checked((int)(4L * gateBlockLength))];

            CopyGateBlock(source, result, directionOffset + 0L * gateBlockLength, 0L * gateBlockLength, gateBlockLength);
            CopyGateBlock(source, result, directionOffset + 2L * gateBlockLength, 1L * gateBlockLength, gateBlockLength);
            CopyGateBlock(source, result, directionOffset + 3L * gateBlockLength, 2L * gateBlockLength, gateBlockLength);
            CopyGateBlock(source, result, directionOffset + 1L * gateBlockLength, 3L * gateBlockLength, gateBlockLength);
            return result;
        }

        protected internal static float[] ReorderOnnxGruGateData(
            float[] source,
            long direction,
            long gateBlockLength,
            long directionStride,
            long offset
        )
        {
            var directionOffset = (direction * directionStride) + offset;
            var result = new float[checked((int)(3L * gateBlockLength))];

            CopyGateBlock(source, result, directionOffset + 1L * gateBlockLength, 0L * gateBlockLength, gateBlockLength);
            CopyGateBlock(source, result, directionOffset + 0L * gateBlockLength, 1L * gateBlockLength, gateBlockLength);
            CopyGateBlock(source, result, directionOffset + 2L * gateBlockLength, 2L * gateBlockLength, gateBlockLength);
            return result;
        }

        protected internal static void CopyGateBlock(
            float[] source,
            float[] target,
            long sourceOffset,
            long targetOffset,
            long length
        )
        {
            Array.Copy(source, checked((int)sourceOffset), target, checked((int)targetOffset), checked((int)length));
        }
    }

    public abstract class TorchSharpModel<TInput, TOutput> : torch.nn.Module<TInput, TOutput>
    {
        protected TorchSharpModel(string name) : base(name)
        {
        }
    }

    public abstract class TorchSharpModel<TInput1, TInput2, TOutput> : torch.nn.Module<TInput1, TInput2, TOutput>
    {
        protected TorchSharpModel(string name) : base(name)
        {
        }
    }

    public abstract class TorchSharpModel<TInput1, TInput2, TInput3, TOutput> : torch.nn.Module<TInput1, TInput2, TInput3, TOutput>
    {
        protected TorchSharpModel(string name) : base(name)
        {
        }
    }

    public abstract class TorchSharpModel<TInput1, TInput2, TInput3, TInput4, TOutput> : torch.nn.Module<TInput1, TInput2, TInput3, TInput4, TOutput>
    {
        protected TorchSharpModel(string name) : base(name)
        {
        }
    }

    public abstract class TorchSharpModel<TInput1, TInput2, TInput3, TInput4, TInput5, TOutput> : torch.nn.Module<TInput1, TInput2, TInput3, TInput4, TInput5, TOutput>
    {
        protected TorchSharpModel(string name) : base(name)
        {
        }
    }

    public abstract class TorchSharpModel<TInput1, TInput2, TInput3, TInput4, TInput5, TInput6, TOutput> : torch.nn.Module<TInput1, TInput2, TInput3, TInput4, TInput5, TInput6, TOutput>
    {
        protected TorchSharpModel(string name) : base(name)
        {
        }
    }

}

#nullable restore
