using System.Text;
using System.Text.Json;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using Onnxify.SourceGenerator.Models;

namespace Onnxify.SourceGenerator
{
    [Generator]
    public class OnnxNodeGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var assemblyName = context.CompilationProvider.Select((c, _) => c.AssemblyName);
            var texts = context.AdditionalTextsProvider;
            var combined = texts.Combine(assemblyName);

            context.RegisterSourceOutput(
                combined,
                (productionContext, sourceContext) =>
                {
                    Generate(
                        context: productionContext,
                        file: sourceContext.Left
                    );
                }
            );
        }

        public void Generate(
            SourceProductionContext context,
            AdditionalText file
        )
        {
            if (Path.GetFileName(file.Path) != "onnx_operators.json")
            {
                return;
            }

            context.ReportDiagnostic(
                Diagnostic.Create(
                    new DiagnosticDescriptor("GEN001", "test", $"Generator running: {file.Path}", "gen", DiagnosticSeverity.Info, true),
                    Location.None
                )
            );

            var json = file.GetText()?.ToString() ?? string.Empty;
            var root = JsonSerializer.Deserialize<OperatorSchemaRoot>(json) ?? throw new Exception();

            var classes = new StringBuilder();

            foreach (var op in root.Operators)
            {
                context.ReportDiagnostic(
                    Diagnostic.Create(
                        new DiagnosticDescriptor("GEN001", "test", op.Name, "gen", DiagnosticSeverity.Warning, true),
                        Location.None
                    )
                );

                var className = $"{op.Name}";

                

                classes.AppendLine($$"""
                public class {{className}} : OnnxNode
                {
                    public {{className}}(
                        string name,
                        IOnnxGraphEdge x,
                        IOnnxGraphEdge w,
                        IOnnxGraphEdge? b,
                        IOnnxGraphEdge y
                    ) : base(
                        name: name,
                        opType: "Conv",
                        domain: "",
                        docString: "",
                        inputs: b is null ? [x, w] : [x, w, b],
                        outputs: [y],
                        attributes: []
                    )
                    {
                    }
                }

                """);
            }

            var namespaceName = $"{nameof(Onnxify)}.Operators";

            var code = $$"""
            // <auto-generated/>
            using System;
            using System.Collections.Generic;
            using Onnxify;
            using Onnx;
                    
            namespace {{namespaceName}}
            {
            {{classes}}
            }
            """;

            context.AddSource($"{namespaceName}.g.cs", SourceText.From(code, Encoding.UTF8));
        }

        // Console.WriteLine("AA");

        /*static string Pascal(string s)
        {
            if (string.IsNullOrEmpty(s))
            {
                return s;
            }

            return char.ToUpperInvariant(s[0]) + s.Substring(1);
        }*/

        /*static string InputName(string name)
        {
            var p = Pascal(name);

            if (p.Equals("Input", StringComparison.OrdinalIgnoreCase))
            {
                return "Input";
            }

            return "Input" + p;
        }*/

        /*static string OutputName(string name)
        {
            var p = Pascal(name);

            if (p.Equals("Output", StringComparison.OrdinalIgnoreCase))
            {
                return "Output";
            }

            return "Output" + p;
        }*/

        /*static string AttributeName(string name)
        {
            var p = Pascal(name);

            if (p.Equals("Attribute", StringComparison.OrdinalIgnoreCase))
            {
                return "Attribute";
            }

            return "Attribute" + p;
        }*/

        /*static string MapType(string type)
        {
            return type switch
            {
                "T" => "TensorProto",
                "Tind" => "TensorProto",
                "T1" => "TensorProto",
                "tensor(int64)" => "TensorProto",
                "tensor(int32)" => "TensorProto",
                "tensor(float)" => "TensorProto",
                "tensor(double)" => "TensorProto",
                "tensor(bool)" => "TensorProto",

                _ => throw new NotSupportedException($"Unsupported ONNX type: {type}")
            };
        }*/

        /*var inputPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Assets", "onnx_operators.json");
        var outputPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "..", "..", "..", "..", "Onnxify", "Operators", "OnnxOperators.cs");

        var root = JsonSerializer.Deserialize<OperatorSchemaRoot>(json) ?? throw new Exception();

        var sourceBuilder = new StringBuilder();

        sourceBuilder.AppendLine($"""
        using Onnx;
        using Onnxify.Abstractions;

        namespace Onnxify.Operators;

        """);

        foreach (var op in root.Operators)
        {
            var propBuilder = new StringBuilder();

            foreach (var x in op.Inputs)
            {
                var required = x.Option == FormalParameterOption.Single ? " required " : " ";
                var nullable = x.Option == FormalParameterOption.Optional ? "?" : "";

                propBuilder.AppendLine($$"""
                    public{{required}}FormalParameter<{{MapType(x.Type)}}>{{nullable}} {{InputName(x.Name)}} { get; set; }
                """);
            }

            if (op.Inputs.Count != 0)
            {
                propBuilder.AppendLine();
            }

            foreach (var x in op.Outputs)
            {
                var required = x.Option == FormalParameterOption.Single ? " required " : " ";
                var nullable = x.Option == FormalParameterOption.Optional ? "?" : "";

                propBuilder.AppendLine($$"""
                    public{{required}}FormalParameter<{{MapType(x.Type)}}>{{nullable}} {{OutputName(x.Name)}} { get; set; }
                """);
            }

            if (op.Outputs.Count != 0)
            {
                propBuilder.AppendLine();
            }

            foreach (var x in op.Attributes)
            {
                var required = x.Required ? " required " : " ";
                var nullable = x.Required ? "" : "?";

                var typeEnum = x.Type;
            
                propBuilder.AppendLine($$"""
                    public{{required}}OperatorAttribute<{{OperatorHelpers.MapAttributeType(typeEnum)}}>{{nullable}} {{AttributeName(x.Name)}} { get; set; }
                """);
            }

            if (op.Attributes.Count != 0)
            {
                propBuilder.AppendLine();
            }

            sourceBuilder.AppendLine($$"""
            /// <summary>
            /// {{op.Name}} operator:
            /// <para>
            /// {{(op.Doc ?? "").Trim().Replace("\n", $"\n/// ")}}
            /// </para>
            /// </summary>
            public sealed class {{op.Name}} : Operator
            {
                public override string Name => "{{op.Name}}";
                public override string Domain => "{{op.Domain}}";
                public override int SinceVersion => {{op.SinceVersion}};

                {{propBuilder.ToString().TrimStart()}}
            }

            """);
        }

        var sourceCode = sourceBuilder.ToString();
        */
        // File.WriteAllText(outputPath, sourceCode);
    }
}
