using System.Text;
using System.Text.Json;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using Onnxify.SourceGenerator.Models;

namespace Onnxify.SourceGenerator;

[Generator]
public sealed class OnnxCompatibilityMetadataGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var relevantFiles = context.AdditionalTextsProvider
            .Where(static file =>
            {
                var fileName = Path.GetFileName(file.Path);
                return string.Equals(fileName, "onnx_operators.json", StringComparison.OrdinalIgnoreCase);
            })
            .Collect();

        context.RegisterSourceOutput(
            relevantFiles,
            (productionContext, files) => Generate(productionContext, files)
        );
    }

    private void Generate(SourceProductionContext context, IReadOnlyList<AdditionalText> files)
    {
        var fileMap = files.ToDictionary(x => Path.GetFileName(x.Path), StringComparer.OrdinalIgnoreCase);

        if (!fileMap.TryGetValue("onnx_operators.json", out var schemaFile))
        {
            return;
        }

        var schemaJson = schemaFile.GetText(context.CancellationToken)?.ToString() ?? string.Empty;
        var schemaRoot = JsonSerializer.Deserialize<OperatorSchemaRoot>(schemaJson);
        if (schemaRoot is null)
        {
            return;
        }

        var historicalSchemas = GetHistoricalOperatorSchemas(schemaRoot.Operators)
            .Select(ToGeneratedSchema)
            .OrderBy(x => x.Domain, StringComparer.Ordinal)
            .ThenBy(x => x.Name, StringComparer.Ordinal)
            .ThenBy(x => x.SinceVersion)
            .ToArray();

        var latestSchemas = GetLatestOperatorSchemas(schemaRoot.Operators)
            .Select(ToGeneratedSchema)
            .OrderBy(x => x.Domain, StringComparer.Ordinal)
            .ThenBy(x => x.Name, StringComparer.Ordinal)
            .ToArray();

        var currentStructuralCompatibility = GetCurrentStructuralCompatibility(schemaRoot.Operators)
            .Select(x => new GeneratedCurrentStructuralCompatibility
            {
                Domain = x.Key.Domain,
                Name = x.Key.Name,
                MinimumCurrentStructureSinceVersion = x.Value,
            })
            .OrderBy(x => x.Domain, StringComparer.Ordinal)
            .ThenBy(x => x.Name, StringComparer.Ordinal)
            .ToArray();

        var historicalSchemaLines = historicalSchemas
            .Select(x => $$"""
            AddHistorical(
                target: historicalSchemas,
                domain: {{AsStringLiteral(x.Domain)}},
                name: {{AsStringLiteral(x.Name)}},
                sinceVersion: {{x.SinceVersion}},
                minimumInputs: {{x.MinimumInputs}},
                maximumInputs: {{AsNullableIntLiteral(x.MaximumInputs)}},
                minimumOutputs: {{x.MinimumOutputs}},
                maximumOutputs: {{AsNullableIntLiteral(x.MaximumOutputs)}},
                knownAttributes: {{AsStringArrayLiteral(x.KnownAttributes)}},
                requiredAttributes: {{AsStringArrayLiteral(x.RequiredAttributes)}}
            );
            """)
            .ToArray();

        var latestSchemaLines = latestSchemas
            .Select(x => $$"""
            latestSchemas[new OperatorKey({{AsStringLiteral(x.Domain)}}, {{AsStringLiteral(x.Name)}})] = new OnnxBundledOperatorSchema
            {
                Domain = {{AsStringLiteral(x.Domain)}},
                Name = {{AsStringLiteral(x.Name)}},
                SinceVersion = {{x.SinceVersion}},
                MinimumInputs = {{x.MinimumInputs}},
                MaximumInputs = {{AsNullableIntLiteral(x.MaximumInputs)}},
                MinimumOutputs = {{x.MinimumOutputs}},
                MaximumOutputs = {{AsNullableIntLiteral(x.MaximumOutputs)}},
                KnownAttributes = new HashSet<string>({{AsStringArrayLiteral(x.KnownAttributes)}}, System.StringComparer.Ordinal),
                RequiredAttributes = new HashSet<string>({{AsStringArrayLiteral(x.RequiredAttributes)}}, System.StringComparer.Ordinal),
                SourceDescription = "generated latest-schema metadata",
            };
            """)
            .ToArray();

        var currentStructuralCompatibilityLines = currentStructuralCompatibility
            .Select(x => $$"""
            currentStructuralCompatibility[new OperatorKey({{AsStringLiteral(x.Domain)}}, {{AsStringLiteral(x.Name)}})] = {{x.MinimumCurrentStructureSinceVersion}};
            """)
            .ToArray();

        var code = $$"""
        // <auto-generated/>
        #nullable enable

        using System.Collections.Generic;

        namespace Onnxify;

        internal static partial class OnnxGeneratedCompatibilityMetadata
        {
            internal static partial void PopulateHistoricalSchemas(
                Dictionary<OperatorKey, SortedDictionary<int, OnnxBundledOperatorSchema>> historicalSchemas
            )
            {
                static void AddHistorical(
                    Dictionary<OperatorKey, SortedDictionary<int, OnnxBundledOperatorSchema>> target,
                    string domain,
                    string name,
                    int sinceVersion,
                    int minimumInputs,
                    int? maximumInputs,
                    int minimumOutputs,
                    int? maximumOutputs,
                    string[] knownAttributes,
                    string[] requiredAttributes
                )
                {
                    var key = new OperatorKey(domain, name);

                    if (!target.TryGetValue(key, out var versions))
                    {
                        versions = new SortedDictionary<int, OnnxBundledOperatorSchema>();
                        target.Add(key, versions);
                    }

                    versions[sinceVersion] = new OnnxBundledOperatorSchema
                    {
                        Domain = domain,
                        Name = name,
                        SinceVersion = sinceVersion,
                        MinimumInputs = minimumInputs,
                        MaximumInputs = maximumInputs,
                        MinimumOutputs = minimumOutputs,
                        MaximumOutputs = maximumOutputs,
                        KnownAttributes = new HashSet<string>(knownAttributes, System.StringComparer.Ordinal),
                        RequiredAttributes = new HashSet<string>(requiredAttributes, System.StringComparer.Ordinal),
                        SourceDescription = "generated historical-schema metadata",
                    };
                }

                {{string.Join("\n\n", historicalSchemaLines).Indent(2)}}
            }

            internal static partial void PopulateLatestSchemas(
                Dictionary<OperatorKey, OnnxBundledOperatorSchema> latestSchemas
            )
            {
                {{(latestSchemaLines.Length > 0 
                    ? string.Join("\n\n", latestSchemaLines).Indent(2) 
                    : string.Empty)}}
            }

            internal static partial void PopulateCurrentStructuralCompatibility(
                Dictionary<OperatorKey, int> currentStructuralCompatibility
            )
            {
                {{(currentStructuralCompatibilityLines.Length > 0 
                    ? string.Join("\n", currentStructuralCompatibilityLines).Indent(2) 
                    : string.Empty)}}
            }
        }
        #nullable restore
        """;

        context.AddSource("OnnxGeneratedCompatibilityMetadata.g.cs", SourceText.From(code, Encoding.UTF8));
    }

    internal static IReadOnlyList<OperatorSchema> GetHistoricalOperatorSchemas(IEnumerable<OperatorSchema> operators)
    {
        return operators
            .GroupBy(x => (Domain: x.Domain, Name: x.Name, SinceVersion: x.SinceVersion))
            .Select(x => x.First())
            .OrderBy(x => x.Domain, StringComparer.Ordinal)
            .ThenBy(x => x.Name, StringComparer.Ordinal)
            .ThenBy(x => x.SinceVersion)
            .ToArray();
    }

    internal static IReadOnlyList<OperatorSchema> GetLatestOperatorSchemas(IEnumerable<OperatorSchema> operators)
    {
        return operators
            .GroupBy(x => (Domain: x.Domain, Name: x.Name))
            .Select(x => x.OrderByDescending(schema => schema.SinceVersion).First())
            .OrderBy(x => x.Domain, StringComparer.Ordinal)
            .ThenBy(x => x.Name, StringComparer.Ordinal)
            .ToArray();
    }

    internal static IReadOnlyDictionary<(string Domain, string Name), int> GetCurrentStructuralCompatibility(IEnumerable<OperatorSchema> operators)
    {
        return operators
            .GroupBy(x => (x.Domain, x.Name))
            .Select(x =>
            {
                var versions = x.OrderBy(schema => schema.SinceVersion).ToArray();
                var latest = versions[versions.Length - 1];
                var latestStructure = GetStructuralSignature(latest);

                var minimumCurrentStructureSinceVersion = versions
                    .Where(schema => string.Equals(GetStructuralSignature(schema), latestStructure, StringComparison.Ordinal))
                    .Min(schema => schema.SinceVersion);

                return new KeyValuePair<(string Domain, string Name), int>(
                    (latest.Domain, latest.Name),
                    minimumCurrentStructureSinceVersion);
            })
            .OrderBy(x => x.Key.Domain, StringComparer.Ordinal)
            .ThenBy(x => x.Key.Name, StringComparer.Ordinal)
            .ToDictionary(x => x.Key, x => x.Value);
    }

    private static GeneratedOperatorSchema ToGeneratedSchema(OperatorSchema schema)
    {
        return new GeneratedOperatorSchema
        {
            Domain = schema.Domain,
            Name = schema.Name,
            SinceVersion = schema.SinceVersion,
            MinimumInputs = CountMinimumParameters(schema.Inputs),
            MaximumInputs = CountMaximumParameters(schema.Inputs),
            MinimumOutputs = CountMinimumParameters(schema.Outputs),
            MaximumOutputs = CountMaximumParameters(schema.Outputs),
            KnownAttributes = schema.Attributes
                .Select(x => x.Name)
                .OrderBy(x => x, StringComparer.Ordinal)
                .ToArray(),
            RequiredAttributes = schema.Attributes
                .Where(x => x.Required)
                .Select(x => x.Name)
                .OrderBy(x => x, StringComparer.Ordinal)
                .ToArray(),
        };
    }

    private static int CountMinimumParameters(IReadOnlyList<OperatorParameter> parameters)
    {
        var count = 0;
        foreach (var parameter in parameters)
        {
            count += parameter.Option switch
            {
                FormalParameterOption.Single => 1,
                FormalParameterOption.Optional => 0,
                FormalParameterOption.Variadic => parameter.MinArity,
                _ => 0,
            };
        }

        return count;
    }

    private static int? CountMaximumParameters(IReadOnlyList<OperatorParameter> parameters)
    {
        var count = 0;
        foreach (var parameter in parameters)
        {
            switch (parameter.Option)
            {
                case FormalParameterOption.Single:
                case FormalParameterOption.Optional:
                    count++;
                    break;
                case FormalParameterOption.Variadic:
                    return null;
            }
        }

        return count;
    }

    private static string AsStringLiteral(string value)
    {
        return "\"" + value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\r", "\\r")
            .Replace("\n", "\\n")
            .Replace("\t", "\\t") + "\"";
    }

    private static string AsNullableIntLiteral(int? value)
    {
        return value is null ? "null" : value.Value.ToString();
    }

    private static string AsStringArrayLiteral(IReadOnlyList<string> values)
    {
        if (values.Count == 0)
        {
            return "System.Array.Empty<string>()";
        }

        return $"new string[] {{ {string.Join(", ", values.Select(AsStringLiteral))} }}";
    }

    private static string GetStructuralSignature(OperatorSchema schema)
    {
        var inputs = string.Join(
            ";",
            schema.Inputs.Select(x => $"{x.Name}|{(int)x.Option}|{x.MinArity}"));

        var outputs = string.Join(
            ";",
            schema.Outputs.Select(x => $"{x.Name}|{(int)x.Option}|{x.MinArity}"));

        var attributes = string.Join(
            ";",
            schema.Attributes
                .OrderBy(x => x.Name, StringComparer.Ordinal)
                .Select(x => $"{x.Name}|{x.Required}|{x.Type}"));

        return $"I[{inputs}]O[{outputs}]A[{attributes}]";
    }

    private sealed class GeneratedOperatorSchema
    {
        public required string Domain { get; set; }
        public required string Name { get; set; }
        public required int SinceVersion { get; set; }
        public required int MinimumInputs { get; set; }
        public required int? MaximumInputs { get; set; }
        public required int MinimumOutputs { get; set; }
        public required int? MaximumOutputs { get; set; }
        public required string[] KnownAttributes { get; set; }
        public required string[] RequiredAttributes { get; set; }
    }

    private sealed class GeneratedCurrentStructuralCompatibility
    {
        public required string Domain { get; set; }
        public required string Name { get; set; }
        public required int MinimumCurrentStructureSinceVersion { get; set; }
    }
}
