using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Onnxify.SourceGenerator
{
    [Generator]
    public class ProtoSchemaGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var assemblyName = context.CompilationProvider.Select((c, _) => c.AssemblyName);
            var texts = context.AdditionalTextsProvider;
            var combined = texts.Combine(assemblyName);

            context.RegisterSourceOutput(
                combined,
                (productionContext, sourceContext) =>
                {
                    Generate(
                        context: productionContext,
                        file: sourceContext.Left
                    );
                }
            );
        }

        public void Generate(
            SourceProductionContext context,
            AdditionalText file
        )
        {
            var className = $"{nameof(Onnxify)}ResourceProvider";

            var code = $$"""
            // <auto-generated/>
            using System;
            using System.Collections.Generic;
                    
            namespace {{nameof(Onnxify)}}
            {
                public static class {{className}}
                {
                    public static readonly byte[] DefaultModel;
                    
                    static {{className}}()
                    {
                        DefaultModel = [1, 2, 3, 4];
                    }
                    
                    static byte[] Base64Decode(string base64EncodedData) 
                    {
                        var result = System.Convert.FromBase64String(base64EncodedData);
                        return result;
                    }
                }
            }
            """;

            context.AddSource($"{className}.g.cs", SourceText.From(code, Encoding.UTF8));
        }
    }
}
